---
title: "Using the MAb Metadata, Sequences, and Alignments"
author: "Jason Taylor"
date: "2023-06-21"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using the MAb Metadata, Sequences, and Alignments}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<style>
table {
    max-width: 100%;
    max-height: 600px;
    overflow: scroll;
}
thead{
    position: sticky;
    top: 0px;
    background-color: #fff;
}
</style>



## Purpose

The purpose of this feature is to offer users sequences and sequence alignments precomputed from V-Quest and IgBLAST.

## Our sources

The sequences presented here have been aquired from the Los Alamos National Laboratory (LANL) and select publications.

## Usage caveats

STUB

## Understanding the `mabMetadata` object

## Tutorial for using sequence and alignment data

Connect to DataSpace via the R API.


```r
library(DataSpaceR)
con <- connectDS()
```

Access metadata for a subset of neutralizing antibody assay (NAb) data...


```r

con$filterMabGrid("mab_mixture", "VRC01")
mab <- con$getMab()
mab$mabMetadata$loadAlignments()
met <- mab$mabMetadata
met
#> <DataSpaceMabMetadata>
#>   URL: https://dataspace-staging.cavd.org
#>   User: jmtaylor@fredhutch.org
#>   Summary:
#>     - 1 mabs
#>   MAbs in metadata: 
#>      VRC01
#>   MAb sequences available:
#>      VRC01
#>   MAb sequences loaded:
#>      VRC01
```

...or from all available metadata.


```r

met <- con$getMabMetadata()
met$loadAlignments()
met 
#> <DataSpaceMabMetadata>
#>   URL: https://dataspace-staging.cavd.org
#>   User: jmtaylor@fredhutch.org
#>   Summary:
#>     - 932 mabs
#>   MAbs in metadata: 
#>      PGT128, 4E10, AB-000440-1, AB-000441-1, AB-000442-1, AB-000443-1, AB-0...
#>   MAb sequences available:
#>      PGT128, b12, PGDM1400, PG16, CH27, CH28, CH31, CH58, CH59, PG9, PGT121...
#>   MAb sequences loaded:
#>      PGT128, b12, PGDM1400, PG16, CH27, CH28, CH31, CH58, CH59, PG9, PGT121...
```

As shown above, the metadata object does not contain sequences and alignments by default but must be loaded to the object manually.

The `loadAlignements` method can also take a charactor vector argument of which mAbs to load sequences and alignments for. In the example below we load sequence and alignment data for all the mAbs where `mab_donor_clade` is listed as `A`.


```r

met <- con$getMabMetadata()
mabIds <- met$mabMetadata[mab_donor_clade == "A" & sequence_available == TRUE, mab_id]
met$loadAlignments(mabIds)
met 
#> <DataSpaceMabMetadata>
#>   URL: https://dataspace-staging.cavd.org
#>   User: jmtaylor@fredhutch.org
#>   Summary:
#>     - 932 mabs
#>   MAbs in metadata: 
#>      PGT128, 4E10, AB-000440-1, AB-000441-1, AB-000442-1, AB-000443-1, AB-0...
#>   MAb sequences available:
#>      PGT128, b12, PGDM1400, PG16, CH27, CH28, CH31, CH58, CH59, PG9, PGT121...
#>   MAb sequences loaded:
#>      CH31, PGT121, PGT123, CH01, PGC14, VRC-CH30, VRC-CH32, VRC-CH33, VRC-C...
```

Once sequences and alignments are loaded, there are several active bindings available to access those data:


```
#>          mab_id sequence_id locus
#>  1: cds_mab_224  cds_seq_82   IGH
#>  2: cds_mab_224  cds_seq_83   IGK
#>  3:  cds_mab_26 cds_seq_108   IGH
#>  4:  cds_mab_26 cds_seq_109   IGL
#>  5:  cds_mab_27 cds_seq_112   IGH
#>  6:  cds_mab_27 cds_seq_113   IGL
#>  7: cds_mab_332 cds_seq_143   IGK
#>  8: cds_mab_332 cds_seq_144   IGH
#>  9: cds_mab_636  cds_seq_60   IGH
#> 10: cds_mab_636  cds_seq_61   IGL
#> 11: cds_mab_641  cds_seq_80   IGH
#> 12: cds_mab_641  cds_seq_81   IGK
#> 13: cds_mab_642  cds_seq_84   IGH
#> 14: cds_mab_642  cds_seq_85   IGK
#> 15: cds_mab_643  cds_seq_86   IGH
#> 16: cds_mab_643  cds_seq_87   IGK
#> 17: cds_mab_644  cds_seq_88   IGH
#> 18: cds_mab_644  cds_seq_89   IGK
#> 19: cds_mab_651 cds_seq_110   IGL
#> 20: cds_mab_651 cds_seq_111   IGH
#> 21: cds_mab_657 cds_seq_141   IGK
#> 22: cds_mab_657 cds_seq_142   IGH
#> 23: cds_mab_658 cds_seq_145   IGK
#> 24: cds_mab_658 cds_seq_146   IGH
#> 25: cds_mab_659 cds_seq_147   IGK
#> 26: cds_mab_659 cds_seq_148   IGH
#> 27: cds_mab_669 cds_seq_171   IGL
#> 28: cds_mab_669 cds_seq_172   IGH
#> 29: cds_mab_670 cds_seq_173   IGH
#> 30: cds_mab_670 cds_seq_174   IGL
#> 31: cds_mab_690 cds_seq_225   IGH
#> 32: cds_mab_690 cds_seq_226   IGL
#>          mab_id sequence_id locus
#>                                                                                                                      header
#>  1: VRC-CH31_JN159435_Homo_sapiens_isolate_VRC-CH31_anti-HIV-1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#>  2: VRC-CH31_JN159438_Homo_sapiens_isolate_VRC-CH31_anti-HIV-1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#>  3:       PGT121_JN201894_Homo_sapiens_isolate_PGT121_anti-HIV_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#>  4:       PGT121_JN201911_Homo_sapiens_isolate_PGT121_anti-HIV_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#>  5:       PGT123_JN201896_Homo_sapiens_isolate_PGT123_anti-HIV_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#>  6:       PGT123_JN201913_Homo_sapiens_isolate_PGT123_anti-HIV_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#>  7:          CH01_JQ267519_Homo_sapiens_isolate_CH01_anti-HIV1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#>  8:          CH01_JQ267523_Homo_sapiens_isolate_CH01_anti-HIV1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#>  9:         PGC14_GU272051_Homo_sapiens_isolate_PGC14_anti-HIV_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 10:         PGC14_GU272052_Homo_sapiens_isolate_PGC14_anti-HIV_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 11: VRC-CH30_JN159434_Homo_sapiens_isolate_VRC-CH30_anti-HIV-1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 12: VRC-CH30_JN159437_Homo_sapiens_isolate_VRC-CH30_anti-HIV-1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 13: VRC-CH32_JN159436_Homo_sapiens_isolate_VRC-CH32_anti-HIV-1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 14: VRC-CH32_JN159439_Homo_sapiens_isolate_VRC-CH32_anti-HIV-1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 15: VRC-CH33_JN159472_Homo_sapiens_isolate_VRC-CH33_anti-HIV-1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 16: VRC-CH33_JN159470_Homo_sapiens_isolate_VRC-CH33_anti-HIV-1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 17: VRC-CH34_JN159473_Homo_sapiens_isolate_VRC-CH34_anti-HIV-1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 18: VRC-CH34_JN159471_Homo_sapiens_isolate_VRC-CH34_anti-HIV-1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 19:       PGT122_JN201912_Homo_sapiens_isolate_PGT122_anti-HIV_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 20:       PGT122_JN201895_Homo_sapiens_isolate_PGT122_anti-HIV_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 21:          CH04_JQ267522_Homo_sapiens_isolate_CH04_anti-HIV1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 22:          CH04_JQ267526_Homo_sapiens_isolate_CH04_anti-HIV1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 23:          CH02_JQ267520_Homo_sapiens_isolate_CH02_anti-HIV1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 24:          CH02_JQ267524_Homo_sapiens_isolate_CH02_anti-HIV1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 25:          CH03_JQ267521_Homo_sapiens_isolate_CH03_anti-HIV1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 26:          CH03_JQ267525_Homo_sapiens_isolate_CH03_anti-HIV1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 27: VRC-PG19_KF515515_Homo_sapiens_isolate_VRC-PG19_anti-HIV-1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 28: VRC-PG19_KF515516_Homo_sapiens_isolate_VRC-PG19_anti-HIV-1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 29: VRC-PG20_KF515514_Homo_sapiens_isolate_VRC-PG20_anti-HIV-1_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 30: VRC-PG20_KF515513_Homo_sapiens_isolate_VRC-PG20_anti-HIV-1_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#> 31:     PGT124_KM507479_Homo_sapiens_isolate_PGT124HC_anti-HIV_immunoglobulin_heavy_chain_variable_region_mRNA,_partial_cds
#> 32:     PGT124_KM507480_Homo_sapiens_isolate_PGT124LC_anti-HIV_immunoglobulin_light_chain_variable_region_mRNA,_partial_cds
#>                                                                                                                      header
#>                     source
#>  1: LANL Sequence Database
#>  2: LANL Sequence Database
#>  3: LANL Sequence Database
#>  4: LANL Sequence Database
#>  5: LANL Sequence Database
#>  6: LANL Sequence Database
#>  7: LANL Sequence Database
#>  8: LANL Sequence Database
#>  9: LANL Sequence Database
#> 10: LANL Sequence Database
#> 11: LANL Sequence Database
#> 12: LANL Sequence Database
#> 13: LANL Sequence Database
#> 14: LANL Sequence Database
#> 15: LANL Sequence Database
#> 16: LANL Sequence Database
#> 17: LANL Sequence Database
#> 18: LANL Sequence Database
#> 19: LANL Sequence Database
#> 20: LANL Sequence Database
#> 21: LANL Sequence Database
#> 22: LANL Sequence Database
#> 23: LANL Sequence Database
#> 24: LANL Sequence Database
#> 25: LANL Sequence Database
#> 26: LANL Sequence Database
#> 27: LANL Sequence Database
#> 28: LANL Sequence Database
#> 29: LANL Sequence Database
#> 30: LANL Sequence Database
#> 31: LANL Sequence Database
#> 32: LANL Sequence Database
#>                     source
#>                                                                                                                                                                                                                                                                                                                                                                                                          sequence_nt
#>  1:        CAGGTGCAGCTGGTGCAGTCAGGGGCTGCCGTGAGGAAGCCTGGGGCCTCAGTGACTGTCTCCTGTAAATTCGCTGAAGACGACGACTACTCTCCATACTGGGTGAATCCGGCCCCTGAACATTTTATTCACTTTTTGCGACAGGCCCCTGGACAACAACTAGAGTGGCTGGCATGGATGAACCCAACGAATGGCGCCGTTAATTATGCATGGTACCTTAATGGCAGGGTCACGGCGACCAGGGACAGGTCCATGACTACAGCCTTTTTGGAAGTGAAGAGTCTAAGATCTGACGACACGGCCGTCTACTATTGTGCGAGGGCCCAGAAAAGGGGGCGGAGTGAGTGGGCCTACGCCCACTGGGGTCAGGGCACTCCGGTCGTCGTCTCGTCA
#>  2:                                                                                            GACATCCAGATGACCCAGTCTCCATCGTCCCTGTCTGCATCACTCGGGGACAGAGTCACCATCACTTGCCAGGCGAGTCGGGGCATTGGCAAAGATTTAAATTGGTACCAGCAGAAAGCGGGAAAAGCCCCTAAGTTACTGGTCTCTGATGCATCCACTTTGGAAGGGGGGGTCCCATCAAGGTTCAGTGGGAGTGGATTTCACCAAAATTTTAGTCTGACTATCAGCAGCCTGCAGGCTGAGGATGTTGCAACATACTTCTGTCAACAATACGAGACTTTTGGCCAGGGGACCAAGGTGGACATCAAA
#>  3:     CAGATGCAGTTACAGGAGTCGGGCCCCGGACTGGTGAAGCCTTCGGAAACCCTGTCCCTCACGTGCAGTGTGTCTGGTGCCTCCATAAGTGACAGTTACTGGAGCTGGATCCGGCGGTCCCCAGGGAAGGGACTTGAGTGGATTGGGTATGTCCACAAAAGCGGCGACACAAATTACAGCCCCTCCCTCAAGAGTCGAGTCAACTTGTCGTTAGACACGTCCAAAAATCAGGTGTCCCTGAGCCTTGTGGCCGCGACCGCTGCGGACTCGGGCAAATATTATTGCGCGAGAACACTGCACGGGAGGAGAATTTATGGAATCGTTGCCTTCAATGAGTGGTTCACCTACTTCTACATGGACGTCTGGGGCAATGGGACTCAGGTCACCGTCTCCTCA
#>  4:                                                                                      TCCGATATATCTGTGGCCCCAGGAGAGACGGCCAGGATTTCCTGTGGGGAAAAGAGCCTTGGAAGTAGAGCTGTACAATGGTATCAACACAGGGCCGGCCAGGCCCCCTCTTTAATCATATATAATAATCAGGACCGGCCCTCAGGGATCCCTGAGCGATTCTCTGGCTCCCCTGACTCCCCTTTTGGGACCACGGCCACCCTGACCATCACCAGTGTCGAAGCCGGGGATGAGGCCGACTATTACTGTCATATATGGGATAGTAGAGTTCCCACCAAATGGGTCTTCGGCGGAGGGACCACGCTGACCGTGTTA
#>  5:     CAGCTGCACCTGCAGGAGTCGGGCCCAGGGCTGGTGAAGCCTCCGGAGACCCTGTCCCTCACGTGTAGTGTGTCTGGCGCCTCCATCAATGATGCCTATTGGAGTTGGATTCGGCAGTCCCCAGGGAAGCGGCCTGAGTGGGTTGGATATGTCCATCACAGCGGTGACACAAATTATAATCCCTCACTCAAGAGGCGCGTCACGTTTTCATTAGACACGGCCAAGAATGAAGTGTCCCTGAAATTAGTAGACCTGACCGCTGCGGACTCGGCCACATATTTTTGTGCGCGAGCACTTCACGGGAAGAGGATTTATGGGATAGTTGCCCTCGGAGAGTTGTTCACCTACTTCTACATGGACGTCTGGGGCAAGGGGACTGCGGTCACCGTCTCCTCA
#>  6:                                                                                      TCCTCTATGTCCGTGTCCCCGGGGGAGACGGCCAAGATCTCCTGTGGAAAAGAGAGCATTGGTAGCAGAGCTGTGCAATGGTATCAGCAGAAGCCAGGCCAGCCCCCCTCATTGATTATCTATAATAATCAGGACCGCCCCGCAGGGGTCCCTGAGCGATTCTCTGCCTCCCCTGACTTCCGTCCTGGGACCACGGCCACCCTGACCATCACCAATGTCGACGCCGAGGATGAGGCCGACTATTACTGTCATATATATGATGCTAGAGGTGGCACCAATTGGGTCTTCGACAGAGGGACCACACTGACCGTCTTA
#>  7:                                                                            GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCCGTACACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>  8: GAGGTTCAGCTGGTGGAGTCTGGGGCAAATGTTGTACGGCCGGGGGGGTCCCTGAGACTCTCCTGTAAAGCGTCCGGATTCATCTTTGAAAATTTTGGTTTTAGTTGGGTCCGCCAGGCTCCAGGGAAGGGGCTTCAGTGGGTCGCTGGTCTTAATTGGAATGGTGGTGACACACGTTATGCAGACTCTGTGAAGGGCCGATTCAGAATGTCCAGAGACAACTCCAGGAATTTTGTGTATTTGGACATGGATAAAGTGGGAGTCGACGACACGGCCTTCTATTACTGTGCGAGAGGGACCGATTACACTATTGACGACGCGGGGATCCATTACCAAGGTTCGGGGACCTTCTGGTACTTCGATCTCTGGGGCCGTGGCACCCTGGTCAGTGTCTCTTCAG
#>  9:                                   GACGGCCACCTGGTTCAGTCTGGGGTTGAGGTGAAGAAGACTGGGGCTACAGTCAAAATCTCCTGCAAGGTTTCTGGATACAGCTTCATCGACTACTACCTTCATTGGGTGCAACGGGCCCCTGGAAAAGGCCTTGAGTGGGTGGGACTTATTGATCCTGAAAATGGTGAGGCTCGATATGCAGAGAAGTTCCAGGGCAGAGTCACCATAATCGCGGACACGTCTATAGATACAGGCTACATGGAAATGAGGAGCCTGAAATCTGAGGACACGGCCGTGTATTTCTGTGCAGCAGGTGCCGTGGGGGCTGATTCCGGGAGCTGGTTCGACCCCTGGGGCCAGGGAACTCTGGTCACCGTCTCGAGC
#> 10:                                                                          TCCTATGAACTGACTCAGCCACCCTCAGTGTCCGTGTCCCCAGGACAGACAGCCAGCATCACCTGTTCTGGATCTAAATTGGGGGATAAATATGTTTCCTGGTATCAACTGAGGCCAGGCCAGTCCCCCATACTGGTCATGTATGAAAATGACAGGCGGCCCTCCGGGATCCCTGAGCGATTCTCCGGTTCCAATTCTGGCGACACTGCCACTCTGACCATCAGCGGGACCCAGGCTTTGGATGAGGCTGACTTCTACTGTCAGGCGTGGGAGACCACCACCACCACTTTTGTTTTCTTCGGCGGAGGGACCCAGCTGACCGTTCTA
#> 11:        CAGGTGCAGCTGGTGCAGTCAGGGGCTGCCGTGAGGAAGCCTGGGGCCTCAGTGACTGTCTCCTGCAAATTCGCTGAAGACGACGACTACTCTCCACACTGGGTGAATCCGGCCCCTGAACACTATATTCACTTTCTACGACAGGCCCCTGGACAGCAACTGGAGTGGTTGGCATGGATGAACCCTACGAATGGCGCCGTCAATTATGCATGGCAGCTTCATGGCAGGCTCACGGCGACCAGAGACGGGTCCATGACTACAGCCTTTTTGGAAGTGAGGAGTCTAAGATCTGACGACACGGCCGTCTATTATTGTGCGAGGGCCCAGAAAAGGGGGCGGAGTGAATGGGCCTACGCCCACTGGGGCCAGGGAACCCCGGTCGCCGTCTCCTCA
#> 12:                                                                                            GACATCCAGATGACCCAGTCTCCATCGTCCTTGTCTGCATCACTCGGAGACAGAGTCACCATCACTTGTCAGGCGAGTCGGGGCATTGGTAAAGATTTAAATTGGTACCAGCAGAAACCGGGAAAGGCCCCTAAGTTACTGGTCTCTGATGCATCCATTTTGGAAGGGGGGGTCCCATCAAGGTTCAGTGGGAGTGGATTTCACCAAAATTTTAGTCTGACCATCAGCAGCCTGCAGCCTGAGGATGTTGCGACATACTTCTGTCAGCAGTACGAGACTTTTGGCCAGGGGACCAAAGTGGACATCAAA
#> 13:        CAGGTGCAGCTGGTGCAGTCAGGGGCTGCCGTGAGGAAGCCTGGGGCCTCAGTGACTGTCTCCTGCAAGTTCGCTGAAGACGACGACTTCTCTCCACACTGGGTGAATCCGGCCCCTGAACACTATATTCATTTTCTGCGACAGGCACCTGGACAACAACTAGAGTGGTTGGCATGGATGAAGCCTACGAATGGTGCCGTCAATTATGCATGGCAACTTCAGGGCAGGGTCACGGTGACCAGGGACAGGTCCCAGACTACAGCCTTTTTGGAAGTTAAGAATCTGAGATCTGACGACACGGCCGTCTATTATTGTGCGAGGGCCCAGAAAAGGGGGCGCAGCGAGTGGGCCTATGCCCACTGGGGCCAGGGAACCCCGGTCGTCATCTCCGCA
#> 14:                                                                                            GACATCCAGATGACCCAGTCTCCATCGTCCCTGTCTGCATCACTCGGAGACAGAGTCACCATCACTTGCCAGGCGAGTCGGGGCATTGGCAAAGATTTAAATTGGTACCAACAGAAACCGGGAAGAGCCCCTAAGTTACTAGTCTCTGATGCATCCATTTTGGAAGGGGGGGTCCCAACGAGATTCAGTGGGAGTGGATTTCACCAAAACTTTAGCCTGACCATCAGCAGCCTGCAGGCTGAGGATGTTGCAACATATTTCTGTCAGCAATACGAAACTTTTGGCCAGGGGACCAAGGTGGACATCAAA
#> 15:        CAGGTGCAGCTGGTGCAGTCAGGGGCTGCCGTGAGGAAGCCCGGGGCCTCAATTAGTGTCTCCTGCAAATTCGCTGATGCCGACGACTACTCTCCGCACTGGATGAATCCGGCCCCTGAACACTATATTCACTTTCTGCGCCAGGCCCCTGGACAGCAATTAGAGTGGTTGGCGTGGATGAATCCTACGAATGGCGCCGTTAATTATGCCTGGTACCTTAATGGCAGGGTCACGGCGACCAGAGACAGGTCCATGACCACAGCGTTTCTGGAAGTGAGGAGTCTGAGATCTGACGACACGGCCGTCTATTATTGTGCGAGGGCCCAGAAAAGGGCGCGGAGTGAATGGGCCTACGCCCACTGGGGCCAGGGAACCCCGGTCGTCGTCTCCTCA
#> 16:                                                                                            GACATCCAGATGACCCAGTCTCCATCGTCCTTGTCTGCATCACTCGGAGACAGAGTCACCATCACTTGCCAGGCGAGTCGGGGCATTGGTAAAGATTTAAATTGGTATCAGCAGAAACGGGGAAGAGCCCCTAGGTTACTGGTCTCTGATGCCTCCGTTTTGGAAGGGGGGGTCCCATCAAGGTTCAGTGGCAGTGGATTTCACCAAAACTTTAGCTTGACCATCAGCACCCTGCAGCCTGAGGATGTTGCGACATACTTCTGTCAGCAGTACGAGACTTTTGGCCAGGGGACCAAAGTGGACATCAAA
#> 17:        CAGGTGCAGCTGGTGCAGTCGGGGGCTGCCGTGAGGAAGCCTGGGGCCTCAGTAACTGTCTCCTGCAAATTCGCTGAAGACGACGACTGGTCTCCACACTGGGTGAATCCGGCCCCTGAACACTATATTCATTTTCTACGGCAGGCCCCTGGACAGCAATTAGAGTGGTTGGCATGGATGAACCCTACAAATGGTGCCGTCAATTATGCATGGCAGCTTAACGGCAGGCTCACGGCGACCAGAGACACGTCCATGACTACAGCCTTTTTGGAGGTGAAGAGTCTGAGATCTGACGACACGGCCGTCTATTATTGTGCGAGGGCCCAAAAAAGGGGGCGCAGTGAATGGGCCTACGCCCACTGGGGCCAGGGAACCCCGGTCGTCGTCTCCTCA
#> 18:                                                                                            GACATCCAGATGACCCAGTCTCCATCGTCCTTGTCTGCATCACTCGGAGACAGAGTCACCATCACTTGCCAGGCGAGCCGGGGTATTGGTAAAGATTTAAATTGGTACCAACAGAAAGCGGGAAAAGCCCCTAAGTTACTGGTCTCTGATGCATCCATTTTGGAAGGGGGGGTCCCATCAAGGTTCAGCGGGAGTGGATTTCACCAAAATTTTAGTCTGACCATCTCCAGCCTGCAGCCTGAAGATGTTGCGACCTATTTCTGTCAGCAGTACGAGACTTTTGGCCAGGGGACCAAGGTGGACATCAAA
#> 19:                                                                                      ACCTTTGTGTCAGTGGCCCCAGGACAGACGGCCAGGATTACTTGTGGGGAAGAGAGCCTTGGAAGTAGATCTGTTATTTGGTATCAACAGAGGCCAGGCCAGGCCCCTTCATTAATCATCTATAATAATAATGACCGGCCCTCAGGGATTCCTGACCGATTTTCTGGGTCCCCTGGCTCCACTTTTGGGACCACGGCCACCCTGACCATCACCAGTGTCGAAGCCGGGGATGAGGCCGACTATTATTGTCATATCTGGGATAGTAGACGACCAACCAATTGGGTCTTCGGCGAAGGGACCACACTGATCGTGTTA
#> 20:     CAGGTTCATCTGCAGGAGTCGGGCCCCGGACTGGTGAAGCCTTCGGAGACCCTGTCCCTCACGTGCAATGTGTCTGGGACCCTCGTGCGTGATAACTACTGGAGCTGGATCAGACAACCCCTCGGGAAGCAACCTGAGTGGATTGGCTATGTCCATGACAGCGGGGACACGAATTACAACCCCTCCCTGAAGAGTCGAGTCCACTTATCGTTGGACAAGTCCAAAAACCTGGTGTCCCTGAGGCTGACCGGCGTGACCGCCGCGGACTCGGCCATATATTATTGCGCGACAACAAAACACGGGAGGAGGATTTATGGCGTCGTTGCCTTCAAAGAGTGGTTCACCTATTTCTACATGGACGTCTGGGGCAAAGGGACTTCGGTCACCGTCTCCTCA
#> 21:                                                                            GAAATTGTGTTGACACAGTCTCCAGACACCCTGTCTTTGTCCCCAGGGGAGAGAGCCACCCTCTCATGCAGGGCCAGTCAGAGTGTTCACAGCAGATACTTTGCCTGGTACCAGCATAAACCTGGCCAGCCTCCCAGACTCCTCATCTATGGTGGGTCCACCAGGGCCACTGGCATCCCTAATAGATTCAGTGCCGGCGGGTCTGGGACACAGTTCACTCTCACCGTCAACAGACTGGAGGCTGAAGATTTTGCGGTATATTACTGTCAGCAGTATGGTCGCTCCCCGTACACGTTCGGCCAAGGGACCAAGGTGGAGATCAGAC
#> 22: GAGGTTCAGCTGGTGGAGTCTGGGGGAGGTCTCATACGGCCGGGGGGGTCCCTGAGACTCTCCTGTAAAGGCTCCGGTTTCATCTTTGAGAATTTTGGCTTCGGCTGGGTCCGCCAAGGTCCAGGGAAGGGGCTGGAGTGGGTGTCTGGCACTAATTGGAATGGAGGTGACTCACGTTATGGAGACTCTGTGAAGGGCCGATTCACAATCTCCAGAGACAACAGCAACAATTTCGTCTACCTGCAAATGAACAGTCTGAGACCCGAGGACACGGCCATATATTATTGTGCGAGAGGGACCGATTACACTATTGACGATCAGGGGATCCGTTATCAAGGTTCGGGGACTTTCTGGTACTTCGATGTCTGGGGCCGCGGCACCCTGGTCACGGTCTCCTCAG
#> 23:                                                                            GAAATTGTGTTGACGCAGTCTCCAGCCACCCTGTCTGTGTCTCCGGGGGAGAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAATGTCCACCCCAGATATTTCGCCTGGTATCAACAAAAACGTGGCCAGTCTCCCAGGCTCCTCATCCATAGTGGATCCACCAGGGCCGCTGGCATCGCAGACAGGTTCAGTGGCGGTGGGTCTGGAATGCACTTCACTCTCACCATCACCAGAGTGGAGCCTGAAGATTTTGCAGTCTATTTCTGTCAACAATACGGTGGTTCTCCCTACACGTTCGGCCAGGGGACCAGGGTGGAACTCAGAC
#> 24: GAGGTTCAGCTGGTGGAGTCTGGGGGAAGTGTGGTGCGGCCGGGGGGGTCCCTGAGACTCTCCTGTAGAGCGTCCGGATTCATCTTTGAGAACTATGGCCTGACTTGGGTCCGCCAAGTTCCAGGGAAAGGGCTACATTGGGTCTCCGGGATGAATTGGAATGGTGGTGACACGCGTTATGCAGACTCTGTGAGGGGCCGATTTAGCATGTCCAGAGACAACAGCAACAACATCGCATATCTGCAAATGAATAATCTGAGAGTGGAGGACACGGCCTTGTATTACTGCGCGAGAGGGACCGATTACACGATAGACGACCAGGGAAGATTTTATCAAGGATCGGGGACCTTCTGGTACTTCGATTTTTGGGGCCGTGGCACACTGGTCACTGTCTCTTCAG
#> 25:                                                                            GAAATTGTGTTGACGCAGTCTCCAGCCACCCTGTCTTTGTCTCCGGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAACCTGGCCAGTCTCCCAGGCTCCTCATCTATAGTGGATCCACTAGGGCCGCTGGCATCGCAGACAGGTTCAGTGGCGGTGGGTCTGGAATACACTTCACTCTCACCATCACCAGAGTGGAGCCTGAAGATTTTGCAGTGTATTTCTGCCAACAATACGGTGGTTCCCCCTACACGTTCGGCCAGGGGACCAAGGTGGAACTCAGGC
#> 26: GAGGTTCAGCTGGTGGAGTCTGGGGGAGGTGTGGTGCGGCCGGGGGGGTCCCTGAGACTCTCCTGTGCAGCGTCCGGATTCATTTTTGAGAACTACGGCTTGACTTGGGTCCGCCAAGTTCCAGGGAAAGGGCTGCATTGGGTCTCCGGTATGAATTGGAATGGTGGTGACACGCGTTATGCAGACTCTGTGAGGGGCCGATTCAGCATGTCCAGAGACAACAGCAATAATATCGCATATCTGCAAATGAAAAATCTGAGAGTCGACGACACGGCCTTGTATTACTGTGCGAGAGGGACCGATTACACGATAGACGACCAGGGAATTTTTTATAAAGGTTCGGGGACCTTCTGGTACTTCGATCTCTGGGGCCGTGGCACCCTGGTCACTGTCTCTTCAG
#> 27:                                                                                   CAGTCTGCCCTGACTCAGCCTGCCTCCGTGTCTGGGTCGCCTGGACAGTCGATCACCATCTCCTGCACTGCAAGCAGCGACTTTCGTGGTTTTTCCTCTGTCTCCTGGTACCAGCAAGTCCCGGGCCGGGCCCCCAAACTTCTTATTTTTAGTGTCAATAGACGACCCTCGGGGATTTCTCATCGCTTCTCTGGCTCCAAGTCTGGCAACACGGCCTCCCTGACCATCTCTGGGCTCCAGATTGAAGACGAGGCTGATTATCACTGTAATGCATATGAATTTTTCGGCGGCGGGACCAAGGTCTTCGTCCTTGGTCAG
#> 28:                                         GAGGTGCGTCTGGTGCAATCTGGGGCTGAAGTGAAGAAGCCTGGGGCATCAGTGAGGGTCTCCTGTGCGGCATCTGGATATACGTTCACCGACTTCGACATACACTGGCTGCGCCAGGCCCCCGGAAGAGGGCTTGAGTGGATGGGGTGGGTGAGGCCTCTGGGAGGTGGCGTCAGTTATGCACGCCAGTTTCAGGGCAGGGTCACTATGACCAGGGACTTCTACATCGACACAGCCTTTATGGACTTCAGGAATTTAAAAATGGACGACACGGCCCTCTACTTCTGTGCGAGAATGGGGGCGGCTCGGGAGTGGGACTTCCAGTACTGGGGCCAGGGCACCCGGGTCCTCGTCTCCTCA
#> 29:                                   CAAGTGCATTTAATGCAGTCTGGGACTGAAATGAAGAAGCCTGGGGCCTCAGTGAGGGTCACCTGTCAGACTTCTGGATACACCTTCAGCGACTACTTCATCCACTGGTTGCGACAAGTCCCCGGTCGAGGATTTGAGTGGATGGGTTGGATGAACCCTCAATGGGGTCAAGTCAACTATGCACGGACATTTCAGGGAAGAGTCACGATGACAAGAGACGTTTATAGGGAAGTTGCTTACTTGGACCTGAGGAGCCTGACATTTGCCGACACGGCCGTCTATTTCTGTGCGAGAAGAATGAGGTCCCAGGACCGCGAGTGGGACTTCCAGCACTGGGGCCAGGGCACCCGGATCATCGTTTCGTCA
#> 30:                                                                                                  CAGTCTGCCCTGACTCAGCCTCCCTCCGTGTCTGGGTCTCCCGGACAGTCGATCACCCTCTCCTGCACTGGCGCCTCTACCTCTGTCGCCTGGTATCAACAATACGCAGACAAGGCCCCCCGACTCATCGTTTTTGATGGCAATAAGCGGCCCTCAGACATTTCTAGTCGCTTCTCTGGATCCCAGTCTGGCGGCACGGCCTCCCTGACCATTTCTGGACTCCAGAGTGAAGACGAGGCTTATTATCATTGTAATGCATTTGAATTCTTTGGCGGAGGGACCAAGTTGACCGTCCTCAGTCAG
#> 31:     CAGGTGCAGCTGCAGGAGTCGGGCCCAGGACTGGTGAGACCTTCGGAGACCCTGTCCGTCACCTGCATCGTCTCTGGGGGCTCCATCAGCAATTACTACTGGACTTGGATCCGACAGTCCCCAGGAAAGGGACTGGAGTGGATAGGCTATATTTCTGACAGAGAAACAACGACTTACAATCCCTCCCTCAACAGTCGAGCCGTCATATCACGAGACACGTCGAAAAACCAATTGTCCCTACAATTACGTTCCGTCACCACTGCGGACACGGCCATCTATTTCTGTGCGACAGCGCGCCGAGGACAGAGGATTTATGGAGTGGTTTCATTTGGAGAGTTCTTCTACTACTACTACATGGACGTCTGGGGCAAAGGGACTGCGGTCACCGTCTCCTCA
#> 32:                                                                             TCCTATGTGAGCCCACTGTCAGTGGCCCTGGGGGAGACGGCCAGGATTTCCTGTGGACGACAGGCCCTTGGAAGTAGAGCTGTGCAGTGGTATCAACATAAGCCAGGCCAGGCCCCTATTTTGCTCATCTATAATAATCAAGACCGGCCCTCAGGGATCCCTGAGCGGTTCTCTGGCACCCCTGATATTAATTTTGGGACCACGGCCACCCTGACTATCAGCGGGGTCGAAGTCGGGGATGAAGCCGACTATTACTGTCACATGTGGGACTCTAGAAGTGGTTTCAGTTGGTCTTTCGGCGGGGCGACCAGGCTGACCGTCCTA
#>                                                                                                                                                                                                                                                                                                                                                                                                          sequence_nt
#>            mab_id mab_name_std mab_lanlid sequence_id locus stop_codon
#>    1: cds_mab_332         CH01       2655 cds_seq_143   IGK          F
#>    2: cds_mab_332         CH01       2655 cds_seq_143   IGK          F
#>    3: cds_mab_332         CH01       2655 cds_seq_143   IGK          F
#>    4: cds_mab_332         CH01       2655 cds_seq_143   IGK          F
#>    5: cds_mab_332         CH01       2655 cds_seq_143   IGK          F
#>   ---                                                                 
#> 2333: cds_mab_644     VRC-CH34       2577  cds_seq_89   IGK          F
#> 2334: cds_mab_669     VRC-PG19       3015 cds_seq_171   IGL          F
#> 2335: cds_mab_669     VRC-PG19       3015 cds_seq_172   IGH          F
#> 2336: cds_mab_670     VRC-PG20       3017 cds_seq_173   IGH          F
#> 2337: cds_mab_670     VRC-PG20       3017 cds_seq_174   IGL          F
#>       vj_in_frame productive rev_comp complete_vdj      v_call      d_call
#>    1:           T          T        F            T IGKV3-20*01        <NA>
#>    2:           T          T        F            T IGKV3-20*01        <NA>
#>    3:           T          T        F            T IGKV3-20*01        <NA>
#>    4:           T          T        F            T IGKV3-20*01        <NA>
#>    5:           T          T        F            T IGKV3-20*01        <NA>
#>   ---                                                                     
#> 2333:           T          T        F            T IGKV1-33*01        <NA>
#> 2334:           T          T        F            T IGLV2-14*03        <NA>
#> 2335:           T          T        F            T  IGHV1-2*02 IGHD6-25*01
#> 2336:           T          T        F            T  IGHV1-2*02 IGHD3-10*01
#> 2337:           T          T        F            T IGLV2-14*03        <NA>
#>         j_call
#>    1: IGKJ1*01
#>    2: IGKJ2*01
#>    3: IGKJ2*03
#>    4: IGKJ4*01
#>    5: IGKJ4*02
#>   ---         
#> 2333: IGKJ2*01
#> 2334: IGLJ2*01
#> 2335: IGHJ1*01
#> 2336: IGHJ1*01
#> 2337: IGLJ2*01
#>                                                                                                                                                                                                                                                                                                                                                                                           sequence_alignment
#>    1:                                                                  GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCCGTACACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    2:                                                                  GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCCGTACACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    3:                                                                  GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCCGTACACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    4:                                                                  GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCCGTACACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    5:                                                                  GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCCGTACACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>   ---                                                                                                                                                                                                                                                                                                                                                                                                       
#> 2333:                                  GACATCCAGATGACCCAGTCTCCATCGTCCTTGTCTGCATCACTCGGAGACAGAGTCACCATCACTTGCCAGGCGAGCCGGGGTATT..................GGTAAAGATTTAAATTGGTACCAACAGAAAGCGGGAAAAGCCCCTAAGTTACTGGTCTCTGATGCA.....................TCCATTTTGGAAGGGGGGGTCCCA...TCAAGGTTCAGCGGGAGTGGA......TTTCACCAAAATTTTAGTCTGACCATCTCCAGCCTGCAGCCTGAAGATGTTGCGACCTATTTCTGTCAGCAGTACGAGACTTTTGGCCAGGGGACCAAGGTGGACATCAAA
#> 2334:                                 CAGTCTGCCCTGACTCAGCCTGCCTCC...GTGTCTGGGTCGCCTGGACAGTCGATCACCATCTCCTGCACT...GCAAGCAGCGACTTTCGT.........GGTTTTTCCTCTGTCTCCTGGTACCAGCAAGTCCCGGGCCGGGCCCCCAAACTTCTTATTTTTAGTGTC.....................AATAGACGACCCTCGGGGATTTCT...CATCGCTTCTCTGGCTCCAAG......TCTGGCAACACGGCCTCCCTGACCATCTCTGGGCTCCAGATTGAAGACGAGGCTGATTATCACTGTAATGCATATGAATTTTTCGGCGGCGGGACCAAGGTCTTCGTCCTTG
#> 2335:       GAGGTGCGTCTGGTGCAATCTGGGGCT...GAAGTGAAGAAGCCTGGGGCATCAGTGAGGGTCTCCTGTGCGGCATCTGGATATACGTTC............ACCGACTTCGACATACACTGGCTGCGCCAGGCCCCCGGAAGAGGGCTTGAGTGGATGGGGTGGGTGAGGCCTCTG......GGAGGTGGCGTCAGTTATGCACGCCAGTTTCAG...GGCAGGGTCACTATGACCAGGGACTTCTACATCGACACAGCCTTTATGGACTTCAGGAATTTAAAAATGGACGACACGGCCCTCTACTTCTGTGCGAGAATGGGGGCGGCTCGGGAGTGGGACTTCCAGTACTGGGGCCAGGGCACCCGGGTCCTCGTCTCCTCA
#> 2336: CAAGTGCATTTAATGCAGTCTGGGACT...GAAATGAAGAAGCCTGGGGCCTCAGTGAGGGTCACCTGTCAGACTTCTGGATACACCTTC............AGCGACTACTTCATCCACTGGTTGCGACAAGTCCCCGGTCGAGGATTTGAGTGGATGGGTTGGATGAACCCTCAA......TGGGGTCAAGTCAACTATGCACGGACATTTCAG...GGAAGAGTCACGATGACAAGAGACGTTTATAGGGAAGTTGCTTACTTGGACCTGAGGAGCCTGACATTTGCCGACACGGCCGTCTATTTCTGTGCGAGAAGAATGAGGTCCCAGGACCGCGAGTGGGACTTCCAGCACTGGGGCCAGGGCACCCGGATCATCGTTTCGTCA
#> 2337:                                 CAGTCTGCCCTGACTCAGCCTCCCTCC...GTGTCTGGGTCTCCCGGACAGTCGATCACCCTCTCCTGCACTGGCGCC...........................TCTACCTCTGTCGCCTGGTATCAACAATACGCAGACAAGGCCCCCCGACTCATCGTTTTTGATGGC.....................AATAAGCGGCCCTCAGACATTTCT...AGTCGCTTCTCTGGATCCCAG......TCTGGCGGCACGGCCTCCCTGACCATTTCTGGACTCCAGAGTGAAGACGAGGCTTATTATCATTGTAATGCATTTGAATTCTTTGGCGGAGGGACCAAGTTGACCGTCCTCA
#>                                                                                                                                                                                                                                                                                                                                                                                           germline_alignment
#>    1:                                                                  GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACCNNNNACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    2:                                                                  GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACCGTACACTTTTGGCCAGGGGACCAAGCTGGAGATCAAAC
#>    3:                                                                  GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACCGTACAGTTTTGGCCAGGGGACCAAGCTGGAGATCAAAC
#>    4:                                                                  GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACCNNNCACTTTCGGCGGAGGGACCAAGGTGGAGATCAAAC
#>    5:                                                                  GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACCNNNCACGTTCGGCGGAGGGACCAAGGTGGAGATCAAAC
#>   ---                                                                                                                                                                                                                                                                                                                                                                                                       
#> 2333:                                  GACATCCAGATGACCCAGTCTCCATCCTCCCTGTCTGCATCTGTAGGAGACAGAGTCACCATCACTTGCCAGGCGAGTCAGGACATT..................AGCAACTATTTAAATTGGTATCAGCAGAAACCAGGGAAAGCCCCTAAGCTCCTGATCTACGATGCA.....................TCCAATTTGGAAACAGGGGTCCCA...TCAAGGTTCAGTGGAAGTGGA......TCTGGGACAGATTTTACTTTCACCATCAGCAGCCTGCAGCCTGAAGATATTGCAACATATTACTGTCAACAGTATGANACTTTTGGCCAGGGGACCAAGCTGGAGATCAAA
#> 2334:                                 CAGTCTGCCCTGACTCAGCCTGCCTCC...GTGTCTGGGTCTCCTGGACAGTCGATCACCATCTCCTGCACTGGAACCAGCAGTGACGTTGGT.........GGTTATAACTATGTCTCCTGGTACCAACAACACCCAGGCAAAGCCCCCAAACTCATGATTTATGATGTC.....................AGTAATCGGCCCTCAGGGGTTTCT...AATCGCTTCTCTGGCTCCAAG......TCTGGCAACACGGCCTCCCTGACCATCTCTGGGCTCCAGGCTGAGGACGAGGCTGATTATTACTGCAGCTCATATNNNNNNTTCGGCGGAGGGACCAAGCTGACCGTCCTAG
#> 2335:       CAGGTGCAGCTGGTGCAGTCTGGGGCT...GAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC............ACCGGCTACTATATGCACTGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGATGGATCAACCCTAAC......AGTGGTGGCACAAACTATGCACAGAAGTTTCAG...GGCAGGGTCACCATGACCAGGGACACGTCCATCAGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGAATAGCAGCGGCTNNNNNNNNNNACTTCCAGCACTGGGGCCAGGGCACCCTGGTCACCGTCTCCTCA
#> 2336: CAGGTGCAGCTGGTGCAGTCTGGGGCT...GAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC............ACCGGCTACTATATGCACTGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGATGGATCAACCCTAAC......AGTGGTGGCACAAACTATGCACAGAAGTTTCAG...GGCAGGGTCACCATGACCAGGGACACGTCCATCAGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGANNNNNNNGGTTCGGGGANNNNNNNNNNNACTTCCAGCACTGGGGCCAGGGCACCCTGGTCACCGTCTCCTCA
#> 2337:                                 CAGTCTGCCCTGACTCAGCCTGCCTCC...GTGTCTGGGTCTCCTGGACAGTCGATCACCATCTCCTGCACTGGAACCAGCAGTGACGTTGGT.........GGTTATAACTATGTCTCCTGGTACCAACAACACCCAGGCAAAGCCCCCAAACTCATGATTTATGATGTC.....................AGTAATCGGCCCTCAGGGGTTTCT...AATCGCTTCTCTGGCTCCAAG......TCTGGCAACACGGCCTCCCTGACCATCTCTGGGCTCCAGGCTGAGGACGAGGCTGATTATTACTGCAGCTCATNTGTGGTATTCGGCGGAGGGACCAAGCTGACCGTCCTAG
#>                                                                                                                    sequence_alignment_aa
#>    1:                       EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSPYTFGQGTKVEIK
#>    2:                       EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSPYTFGQGTKVEIK
#>    3:                       EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSPYTFGQGTKVEIK
#>    4:                       EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSPYTFGQGTKVEIK
#>    5:                       EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSPYTFGQGTKVEIK
#>   ---                                                                                                                                   
#> 2333:            DIQMTQSPSSLSASLGDRVTITCQASRGI......GKDLNWYQQKAGKAPKLLVSDA.......SILEGGVP.SRFSGSG..FHQNFSLTISSLQPEDVATYFCQQYETFGQGTKVDIK
#> 2334:            QSALTQPAS.VSGSPGQSITISCT.ASSDFR...GFSSVSWYQQVPGRAPKLLIFSV.......NRRPSGIS.HRFSGSK..SGNTASLTISGLQIEDEADYHCNAYEFFGGGTKVFVL
#> 2335:   EVRLVQSGA.EVKKPGASVRVSCAASGYTF....TDFDIHWLRQAPGRGLEWMGWVRPL..GGGVSYARQFQ.GRVTMTRDFYIDTAFMDFRNLKMDDTALYFCARMGAAREWDFQYWGQGTRVLVSS
#> 2336: QVHLMQSGT.EMKKPGASVRVTCQTSGYTF....SDYFIHWLRQVPGRGFEWMGWMNPQ..WGQVNYARTFQ.GRVTMTRDVYREVAYLDLRSLTFADTAVYFCARRMRSQDREWDFQHWGQGTRIIVSS
#> 2337:            QSALTQPPS.VSGSPGQSITLSCTGA.........STSVAWYQQYADKAPRLIVFDG.......NKRPSDIS.SRFSGSQ..SGGTASLTISGLQSEDEAYYHCNAFEFFGGGTKLTVL
#>                                                                                                                   germline_alignment_aa
#>    1:                      EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPXTFGQGTKVEIK
#>    2:                      EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPYTFGQGTKLEIK
#>    3:                      EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPYSFGQGTKLEIK
#>    4:                      EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPXTFGGGTKVEIK
#>    5:                      EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSPXTFGGGTKVEIK
#>   ---                                                                                                                                  
#> 2333:           DIQMTQSPSSLSASVGDRVTITCQASQDI......SNYLNWYQQKPGKAPKLLIYDA.......SNLETGVP.SRFSGSG..SGTDFTFTISSLQPEDIATYYCQQYXTFGQGTKLEIK
#> 2334:           QSALTQPAS.VSGSPGQSITISCTGTSSDVG...GYNYVSWYQQHPGKAPKLMIYDV.......SNRPSGVS.NRFSGSK..SGNTASLTISGLQAEDEADYYCSSYXXFGGGTKLTVL
#> 2335:  QVQLVQSGA.EVKKPGASVKVSCKASGYTF....TGYYMHWVRQAPGQGLEWMGWINPN..SGGTNYAQKFQ.GRVTMTRDTSISTAYMELSRLRSDDTAVYYCARIAAAXXXXFQHWGQGTLVTVSS
#> 2336: QVQLVQSGA.EVKKPGASVKVSCKASGYTF....TGYYMHWVRQAPGQGLEWMGWINPN..SGGTNYAQKFQ.GRVTMTRDTSISTAYMELSRLRSDDTAVYYCARXXXFGXXXXFQHWGQGTLVTVSS
#> 2337:           QSALTQPAS.VSGSPGQSITISCTGTSSDVG...GYNYVSWYQQHPGKAPKLMIYDV.......SNRPSGVS.NRFSGSK..SGNTASLTISGLQAEDEADYYCSSXVVFGGGTKLTVL
#>       v_alignment_start v_alignment_end d_alignment_start d_alignment_end
#>    1:                 1             287                NA              NA
#>    2:                 1             287                NA              NA
#>    3:                 1             287                NA              NA
#>    4:                 1             287                NA              NA
#>    5:                 1             287                NA              NA
#>   ---                                                                    
#> 2333:                 1             323                NA              NA
#> 2334:                 1             321                NA              NA
#> 2335:                 1             318               319             330
#> 2336:                 1             318               326             335
#> 2337:                 1             319                NA              NA
#>       j_alignment_start j_alignment_end
#>    1:               292             325
#>    2:               288             325
#>    3:               288             325
#>    4:               291             325
#>    5:               291             325
#>   ---                                  
#> 2333:               325             357
#> 2334:               328             358
#> 2335:               341             384
#> 2336:               347             390
#> 2337:               321             358
#>                                                                                                                                                                                                                                                                                                                      v_sequence_alignment
#>    1:                                     GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCC
#>    2:                                     GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCC
#>    3:                                     GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCC
#>    4:                                     GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCC
#>    5:                                     GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCACAATGTCCACCCCAAATATTTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTATGGTGGGTCCACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGTCAGCAGTATGGTGGCTCCCC
#>   ---                                                                                                                                                                                                                                                                                                                                    
#> 2333: GACATCCAGATGACCCAGTCTCCATCGTCCTTGTCTGCATCACTCGGAGACAGAGTCACCATCACTTGCCAGGCGAGCCGGGGTATT..................GGTAAAGATTTAAATTGGTACCAACAGAAAGCGGGAAAAGCCCCTAAGTTACTGGTCTCTGATGCA.....................TCCATTTTGGAAGGGGGGGTCCCA...TCAAGGTTCAGCGGGAGTGGA......TTTCACCAAAATTTTAGTCTGACCATCTCCAGCCTGCAGCCTGAAGATGTTGCGACCTATTTCTGTCAGCAGTACGA
#> 2334:   CAGTCTGCCCTGACTCAGCCTGCCTCC...GTGTCTGGGTCGCCTGGACAGTCGATCACCATCTCCTGCACT...GCAAGCAGCGACTTTCGT.........GGTTTTTCCTCTGTCTCCTGGTACCAGCAAGTCCCGGGCCGGGCCCCCAAACTTCTTATTTTTAGTGTC.....................AATAGACGACCCTCGGGGATTTCT...CATCGCTTCTCTGGCTCCAAG......TCTGGCAACACGGCCTCCCTGACCATCTCTGGGCTCCAGATTGAAGACGAGGCTGATTATCACTGTAATGCATAT
#> 2335:      GAGGTGCGTCTGGTGCAATCTGGGGCT...GAAGTGAAGAAGCCTGGGGCATCAGTGAGGGTCTCCTGTGCGGCATCTGGATATACGTTC............ACCGACTTCGACATACACTGGCTGCGCCAGGCCCCCGGAAGAGGGCTTGAGTGGATGGGGTGGGTGAGGCCTCTG......GGAGGTGGCGTCAGTTATGCACGCCAGTTTCAG...GGCAGGGTCACTATGACCAGGGACTTCTACATCGACACAGCCTTTATGGACTTCAGGAATTTAAAAATGGACGACACGGCCCTCTACTTCTGTGCGAGA
#> 2336:      CAAGTGCATTTAATGCAGTCTGGGACT...GAAATGAAGAAGCCTGGGGCCTCAGTGAGGGTCACCTGTCAGACTTCTGGATACACCTTC............AGCGACTACTTCATCCACTGGTTGCGACAAGTCCCCGGTCGAGGATTTGAGTGGATGGGTTGGATGAACCCTCAA......TGGGGTCAAGTCAACTATGCACGGACATTTCAG...GGAAGAGTCACGATGACAAGAGACGTTTATAGGGAAGTTGCTTACTTGGACCTGAGGAGCCTGACATTTGCCGACACGGCCGTCTATTTCTGTGCGAGA
#> 2337:     CAGTCTGCCCTGACTCAGCCTCCCTCC...GTGTCTGGGTCTCCCGGACAGTCGATCACCCTCTCCTGCACTGGCGCC...........................TCTACCTCTGTCGCCTGGTATCAACAATACGCAGACAAGGCCCCCCGACTCATCGTTTTTGATGGC.....................AATAAGCGGCCCTCAGACATTTCT...AGTCGCTTCTCTGGATCCCAG......TCTGGCGGCACGGCCTCCCTGACCATTTCTGGACTCCAGAGTGAAGACGAGGCTTATTATCATTGTAATGCAT
#>                                                                                           v_sequence_alignment_aa
#>    1:            EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSP
#>    2:            EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSP
#>    3:            EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSP
#>    4:            EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSP
#>    5:            EIVLAQSPGTLSLSPGERATLSCRASHNVHPKYFAWYQQKPGQSPRLLIYGGSTRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYCQQYGGSP
#>   ---                                                                                                            
#> 2333: DIQMTQSPSSLSASLGDRVTITCQASRGI......GKDLNWYQQKAGKAPKLLVSDA.......SILEGGVP.SRFSGSG..FHQNFSLTISSLQPEDVATYFCQQY
#> 2334: QSALTQPAS.VSGSPGQSITISCT.ASSDFR...GFSSVSWYQQVPGRAPKLLIFSV.......NRRPSGIS.HRFSGSK..SGNTASLTISGLQIEDEADYHCNAY
#> 2335:  EVRLVQSGA.EVKKPGASVRVSCAASGYTF....TDFDIHWLRQAPGRGLEWMGWVRPL..GGGVSYARQFQ.GRVTMTRDFYIDTAFMDFRNLKMDDTALYFCAR
#> 2336:  QVHLMQSGT.EMKKPGASVRVTCQTSGYTF....SDYFIHWLRQVPGRGFEWMGWMNPQ..WGQVNYARTFQ.GRVTMTRDVYREVAYLDLRSLTFADTAVYFCAR
#> 2337:  QSALTQPPS.VSGSPGQSITLSCTGA.........STSVAWYQQYADKAPRLIVFDG.......NKRPSDIS.SRFSGSQ..SGGTASLTISGLQSEDEAYYHCNA
#>                                                                                                                                                                                                                                                                                                                      v_germline_alignment
#>    1:                                     GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACC
#>    2:                                     GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACC
#>    3:                                     GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACC
#>    4:                                     GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACC
#>    5:                                     GAAATTGTGTTGACGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGTCAGAGTGTTAGCAGCAGCTACTTAGCCTGGTACCAGCAGAAACCTGGCCAGGCTCCCAGGCTCCTCATCTATGGTGCATCCAGCAGGGCCACTGGCATCCCAGACAGGTTCAGTGGCAGTGGGTCTGGGACAGACTTCACTCTCACCATCAGCAGACTGGAGCCTGAAGATTTTGCAGTGTATTACTGTCAGCAGTATGGTAGCTCACC
#>   ---                                                                                                                                                                                                                                                                                                                                    
#> 2333: GACATCCAGATGACCCAGTCTCCATCCTCCCTGTCTGCATCTGTAGGAGACAGAGTCACCATCACTTGCCAGGCGAGTCAGGACATT..................AGCAACTATTTAAATTGGTATCAGCAGAAACCAGGGAAAGCCCCTAAGCTCCTGATCTACGATGCA.....................TCCAATTTGGAAACAGGGGTCCCA...TCAAGGTTCAGTGGAAGTGGA......TCTGGGACAGATTTTACTTTCACCATCAGCAGCCTGCAGCCTGAAGATATTGCAACATATTACTGTCAACAGTATGA
#> 2334:   CAGTCTGCCCTGACTCAGCCTGCCTCC...GTGTCTGGGTCTCCTGGACAGTCGATCACCATCTCCTGCACTGGAACCAGCAGTGACGTTGGT.........GGTTATAACTATGTCTCCTGGTACCAACAACACCCAGGCAAAGCCCCCAAACTCATGATTTATGATGTC.....................AGTAATCGGCCCTCAGGGGTTTCT...AATCGCTTCTCTGGCTCCAAG......TCTGGCAACACGGCCTCCCTGACCATCTCTGGGCTCCAGGCTGAGGACGAGGCTGATTATTACTGCAGCTCATAT
#> 2335:      CAGGTGCAGCTGGTGCAGTCTGGGGCT...GAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC............ACCGGCTACTATATGCACTGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGATGGATCAACCCTAAC......AGTGGTGGCACAAACTATGCACAGAAGTTTCAG...GGCAGGGTCACCATGACCAGGGACACGTCCATCAGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGA
#> 2336:      CAGGTGCAGCTGGTGCAGTCTGGGGCT...GAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATACACCTTC............ACCGGCTACTATATGCACTGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGATGGATCAACCCTAAC......AGTGGTGGCACAAACTATGCACAGAAGTTTCAG...GGCAGGGTCACCATGACCAGGGACACGTCCATCAGCACAGCCTACATGGAGCTGAGCAGGCTGAGATCTGACGACACGGCCGTGTATTACTGTGCGAGA
#> 2337:     CAGTCTGCCCTGACTCAGCCTGCCTCC...GTGTCTGGGTCTCCTGGACAGTCGATCACCATCTCCTGCACTGGAACCAGCAGTGACGTTGGT.........GGTTATAACTATGTCTCCTGGTACCAACAACACCCAGGCAAAGCCCCCAAACTCATGATTTATGATGTC.....................AGTAATCGGCCCTCAGGGGTTTCT...AATCGCTTCTCTGGCTCCAAG......TCTGGCAACACGGCCTCCCTGACCATCTCTGGGCTCCAGGCTGAGGACGAGGCTGATTATTACTGCAGCTCAT
#>                                                                                           v_germline_alignment_aa
#>    1:            EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSP
#>    2:            EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSP
#>    3:            EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSP
#>    4:            EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSP
#>    5:            EIVLTQSPGTLSLSPGERATLSCRASQSVSSSYLAWYQQKPGQAPRLLIYGASSRATGIPDRFSGSGSGTDFTLTISRLEPEDFAVYYCQQYGSSP
#>   ---                                                                                                            
#> 2333: DIQMTQSPSSLSASVGDRVTITCQASQDI......SNYLNWYQQKPGKAPKLLIYDA.......SNLETGVP.SRFSGSG..SGTDFTFTISSLQPEDIATYYCQQY
#> 2334: QSALTQPAS.VSGSPGQSITISCTGTSSDVG...GYNYVSWYQQHPGKAPKLMIYDV.......SNRPSGVS.NRFSGSK..SGNTASLTISGLQAEDEADYYCSSY
#> 2335:  QVQLVQSGA.EVKKPGASVKVSCKASGYTF....TGYYMHWVRQAPGQGLEWMGWINPN..SGGTNYAQKFQ.GRVTMTRDTSISTAYMELSRLRSDDTAVYYCAR
#> 2336:  QVQLVQSGA.EVKKPGASVKVSCKASGYTF....TGYYMHWVRQAPGQGLEWMGWINPN..SGGTNYAQKFQ.GRVTMTRDTSISTAYMELSRLRSDDTAVYYCAR
#> 2337:  QSALTQPAS.VSGSPGQSITISCTGTSSDVG...GYNYVSWYQQHPGKAPKLMIYDV.......SNRPSGVS.NRFSGSK..SGNTASLTISGLQAEDEADYYCSS
#>       d_sequence_alignment d_sequence_alignment_aa d_germline_alignment
#>    1:                 <NA>                    <NA>                 <NA>
#>    2:                 <NA>                    <NA>                 <NA>
#>    3:                 <NA>                    <NA>                 <NA>
#>    4:                 <NA>                    <NA>                 <NA>
#>    5:                 <NA>                    <NA>                 <NA>
#>   ---                                                                  
#> 2333:                 <NA>                    <NA>                 <NA>
#> 2334:                 <NA>                    <NA>                 <NA>
#> 2335:         ATGGGGGCGGCT                    MGAA         ATAGCAGCGGCT
#> 2336:           GGTCCCAGGA                      SQ           GGTTCGGGGA
#> 2337:                 <NA>                    <NA>                 <NA>
#>       d_germline_alignment_aa                         j_sequence_alignment
#>    1:                    <NA>           ACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    2:                    <NA>       GTACACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    3:                    <NA>       GTACACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    4:                    <NA>          CACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    5:                    <NA>          CACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>   ---                                                                     
#> 2333:                    <NA>            ACTTTTGGCCAGGGGACCAAGGTGGACATCAAA
#> 2334:                    <NA>              TTCGGCGGCGGGACCAAGGTCTTCGTCCTTG
#> 2335:                    IAAA ACTTCCAGTACTGGGGCCAGGGCACCCGGGTCCTCGTCTCCTCA
#> 2336:                      FG ACTTCCAGCACTGGGGCCAGGGCACCCGGATCATCGTTTCGTCA
#> 2337:                    <NA>       TGAATTCTTTGGCGGAGGGACCAAGTTGACCGTCCTCA
#>       j_sequence_alignment_aa                         j_germline_alignment
#>    1:             TFGQGTKVEIK           ACGTTCGGCCAAGGGACCAAGGTGGAAATCAAAC
#>    2:            YTFGQGTKVEIK       GTACACTTTTGGCCAGGGGACCAAGCTGGAGATCAAAC
#>    3:            YTFGQGTKVEIK       GTACAGTTTTGGCCAGGGGACCAAGCTGGAGATCAAAC
#>    4:             TFGQGTKVEIK          CACTTTCGGCGGAGGGACCAAGGTGGAGATCAAAC
#>    5:             TFGQGTKVEIK          CACGTTCGGCGGAGGGACCAAGGTGGAGATCAAAC
#>   ---                                                                     
#> 2333:             TFGQGTKVDIK            ACTTTTGGCCAGGGGACCAAGCTGGAGATCAAA
#> 2334:              FGGGTKVFVL              TTCGGCGGAGGGACCAAGCTGACCGTCCTAG
#> 2335:          FQYWGQGTRVLVSS ACTTCCAGCACTGGGGCCAGGGCACCCTGGTCACCGTCTCCTCA
#> 2336:          FQHWGQGTRIIVSS ACTTCCAGCACTGGGGCCAGGGCACCCTGGTCACCGTCTCCTCA
#> 2337:            EFFGGGTKLTVL       TGTGGTATTCGGCGGAGGGACCAAGCTGACCGTCCTAG
#>       j_germline_alignment_aa
#>    1:             TFGQGTKVEIK
#>    2:            YTFGQGTKLEIK
#>    3:            YSFGQGTKLEIK
#>    4:             TFGGGTKVEIK
#>    5:             TFGGGTKVEIK
#>   ---                        
#> 2333:             TFGQGTKLEIK
#> 2334:              FGGGTKLTVL
#> 2335:          FQHWGQGTLVTVSS
#> 2336:          FQHWGQGTLVTVSS
#> 2337:            VVFGGGTKLTVL
#>                                                                                 fwr1
#>    1: GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGT
#>    2: GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGT
#>    3: GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGT
#>    4: GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGT
#>    5: GAAATTGTGTTGGCGCAGTCTCCAGGCACCCTGTCTTTGTCTCCAGGGGAAAGAGCCACCCTCTCCTGCAGGGCCAGT
#>   ---                                                                               
#> 2333: GACATCCAGATGACCCAGTCTCCATCGTCCTTGTCTGCATCACTCGGAGACAGAGTCACCATCACTTGCCAGGCGAGC
#> 2334:       CAGTCTGCCCTGACTCAGCCTGCCTCCGTGTCTGGGTCGCCTGGACAGTCGATCACCATCTCCTGCACTGCA
#> 2335:    GAGGTGCGTCTGGTGCAATCTGGGGCTGAAGTGAAGAAGCCTGGGGCATCAGTGAGGGTCTCCTGTGCGGCATCT
#> 2336:    CAAGTGCATTTAATGCAGTCTGGGACTGAAATGAAGAAGCCTGGGGCCTCAGTGAGGGTCACCTGTCAGACTTCT
#> 2337:    CAGTCTGCCCTGACTCAGCCTCCCTCCGTGTCTGGGTCTCCCGGACAGTCGATCACCCTCTCCTGCACTGGCGCC
#>                          fwr1_aa                        cdr1   cdr1_aa
#>    1: EIVLAQSPGTLSLSPGERATLSCRAS       CACAATGTCCACCCCAAATAT   HNVHPKY
#>    2: EIVLAQSPGTLSLSPGERATLSCRAS       CACAATGTCCACCCCAAATAT   HNVHPKY
#>    3: EIVLAQSPGTLSLSPGERATLSCRAS       CACAATGTCCACCCCAAATAT   HNVHPKY
#>    4: EIVLAQSPGTLSLSPGERATLSCRAS       CACAATGTCCACCCCAAATAT   HNVHPKY
#>    5: EIVLAQSPGTLSLSPGERATLSCRAS       CACAATGTCCACCCCAAATAT   HNVHPKY
#>   ---                                                                 
#> 2333: DIQMTQSPSSLSASLGDRVTITCQAS          CGGGGTATTGGTAAAGAT    RGIGKD
#> 2334:   QSALTQPASVSGSPGQSITISCTA AGCAGCGACTTTCGTGGTTTTTCCTCT SSDFRGFSS
#> 2335:  EVRLVQSGAEVKKPGASVRVSCAAS    GGATATACGTTCACCGACTTCGAC  GYTFTDFD
#> 2336:  QVHLMQSGTEMKKPGASVRVTCQTS    GGATACACCTTCAGCGACTACTTC  GYTFSDYF
#> 2337:  QSALTQPPSVSGSPGQSITLSCTGA                   TCTACCTCT       STS
#>                                                      fwr2           fwr2_aa
#>    1: TTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTAT FAWYQQKPGQSPRLLIY
#>    2: TTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTAT FAWYQQKPGQSPRLLIY
#>    3: TTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTAT FAWYQQKPGQSPRLLIY
#>    4: TTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTAT FAWYQQKPGQSPRLLIY
#>    5: TTCGCCTGGTACCAGCAGAAGCCTGGCCAGTCTCCCCGACTCCTCATCTAT FAWYQQKPGQSPRLLIY
#>   ---                                                                      
#> 2333: TTAAATTGGTACCAACAGAAAGCGGGAAAAGCCCCTAAGTTACTGGTCTCT LNWYQQKAGKAPKLLVS
#> 2334: GTCTCCTGGTACCAGCAAGTCCCGGGCCGGGCCCCCAAACTTCTTATTTTT VSWYQQVPGRAPKLLIF
#> 2335: ATACACTGGCTGCGCCAGGCCCCCGGAAGAGGGCTTGAGTGGATGGGGTGG IHWLRQAPGRGLEWMGW
#> 2336: ATCCACTGGTTGCGACAAGTCCCCGGTCGAGGATTTGAGTGGATGGGTTGG IHWLRQVPGRGFEWMGW
#> 2337: GTCGCCTGGTATCAACAATACGCAGACAAGGCCCCCCGACTCATCGTTTTT VAWYQQYADKAPRLIVF
#>                           cdr2  cdr2_aa
#>    1:                GGTGGGTCC      GGS
#>    2:                GGTGGGTCC      GGS
#>    3:                GGTGGGTCC      GGS
#>    4:                GGTGGGTCC      GGS
#>    5:                GGTGGGTCC      GGS
#>   ---                                  
#> 2333:                GATGCATCC      DAS
#> 2334:                AGTGTCAAT      SVN
#> 2335: GTGAGGCCTCTGGGAGGTGGCGTC VRPLGGGV
#> 2336: ATGAACCCTCAATGGGGTCAAGTC MNPQWGQV
#> 2337:                GATGGCAAT      DGN
#>                                                                                                                     fwr3
#>    1:       ACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGT
#>    2:       ACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGT
#>    3:       ACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGT
#>    4:       ACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGT
#>    5:       ACCAGGGCCGCTGGCATTCCAGGCAAGTTCAGCGGCAGTGGGTCTGGGACCGACTTCACTCTCACCATCAGTCGAGTGGACCCTGAAGATTTTGCAGTTTATTACTGT
#>   ---                                                                                                                   
#> 2333:       ATTTTGGAAGGGGGGGTCCCATCAAGGTTCAGCGGGAGTGGATTTCACCAAAATTTTAGTCTGACCATCTCCAGCCTGCAGCCTGAAGATGTTGCGACCTATTTCTGT
#> 2334:       AGACGACCCTCGGGGATTTCTCATCGCTTCTCTGGCTCCAAGTCTGGCAACACGGCCTCCCTGACCATCTCTGGGCTCCAGATTGAAGACGAGGCTGATTATCACTGT
#> 2335: AGTTATGCACGCCAGTTTCAGGGCAGGGTCACTATGACCAGGGACTTCTACATCGACACAGCCTTTATGGACTTCAGGAATTTAAAAATGGACGACACGGCCCTCTACTTCTGT
#> 2336: AACTATGCACGGACATTTCAGGGAAGAGTCACGATGACAAGAGACGTTTATAGGGAAGTTGCTTACTTGGACCTGAGGAGCCTGACATTTGCCGACACGGCCGTCTATTTCTGT
#> 2337:       AAGCGGCCCTCAGACATTTCTAGTCGCTTCTCTGGATCCCAGTCTGGCGGCACGGCCTCCCTGACCATTTCTGGACTCCAGAGTGAAGACGAGGCTTATTATCATTGT
#>                                      fwr3_aa                              fwr4
#>    1:   TRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYC    TTCGGCCAAGGGACCAAGGTGGAAATCAAA
#>    2:   TRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYC    TTCGGCCAAGGGACCAAGGTGGAAATCAAA
#>    3:   TRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYC    TTCGGCCAAGGGACCAAGGTGGAAATCAAA
#>    4:   TRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYC    TTCGGCCAAGGGACCAAGGTGGAAATCAAA
#>    5:   TRAAGIPGKFSGSGSGTDFTLTISRVDPEDFAVYYC    TTCGGCCAAGGGACCAAGGTGGAAATCAAA
#>   ---                                                                         
#> 2333:   ILEGGVPSRFSGSGFHQNFSLTISSLQPEDVATYFC    TTTGGCCAGGGGACCAAGGTGGACATCAAA
#> 2334:   RRPSGISHRFSGSKSGNTASLTISGLQIEDEADYHC   TTCGGCGGCGGGACCAAGGTCTTCGTCCTTG
#> 2335: SYARQFQGRVTMTRDFYIDTAFMDFRNLKMDDTALYFC TGGGGCCAGGGCACCCGGGTCCTCGTCTCCTCA
#> 2336: NYARTFQGRVTMTRDVYREVAYLDLRSLTFADTAVYFC TGGGGCCAGGGCACCCGGATCATCGTTTCGTCA
#> 2337:   KRPSDISSRFSGSQSGGTASLTISGLQSEDEAYYHC   TTTGGCGGAGGGACCAAGTTGACCGTCCTCA
#>           fwr4_aa                                          cdr3         cdr3_aa
#>    1:  FGQGTKVEIK                   CAGCAGTATGGTGGCTCCCCGTACACG       QQYGGSPYT
#>    2:  FGQGTKVEIK                   CAGCAGTATGGTGGCTCCCCGTACACG       QQYGGSPYT
#>    3:  FGQGTKVEIK                   CAGCAGTATGGTGGCTCCCCGTACACG       QQYGGSPYT
#>    4:  FGQGTKVEIK                   CAGCAGTATGGTGGCTCCCCGTACACG       QQYGGSPYT
#>    5:  FGQGTKVEIK                   CAGCAGTATGGTGGCTCCCCGTACACG       QQYGGSPYT
#>   ---                                                                          
#> 2333:  FGQGTKVDIK                               CAGCAGTACGAGACT           QQYET
#> 2334:  FGGGTKVFVL                               AATGCATATGAATTT           NAYEF
#> 2335: WGQGTRVLVSS       GCGAGAATGGGGGCGGCTCGGGAGTGGGACTTCCAGTAC   ARMGAAREWDFQY
#> 2336: WGQGTRIIVSS GCGAGAAGAATGAGGTCCCAGGACCGCGAGTGGGACTTCCAGCAC ARRMRSQDREWDFQH
#> 2337:  FGGGTKLTVL                               AATGCATTTGAATTC           NAFEF
#>                                                  junction junction_length
#>    1:                   TGTCAGCAGTATGGTGGCTCCCCGTACACGTTC              33
#>    2:                   TGTCAGCAGTATGGTGGCTCCCCGTACACGTTC              33
#>    3:                   TGTCAGCAGTATGGTGGCTCCCCGTACACGTTC              33
#>    4:                   TGTCAGCAGTATGGTGGCTCCCCGTACACGTTC              33
#>    5:                   TGTCAGCAGTATGGTGGCTCCCCGTACACGTTC              33
#>   ---                                                                    
#> 2333:                               TGTCAGCAGTACGAGACTTTT              21
#> 2334:                               TGTAATGCATATGAATTTTTC              21
#> 2335:       TGTGCGAGAATGGGGGCGGCTCGGGAGTGGGACTTCCAGTACTGG              45
#> 2336: TGTGCGAGAAGAATGAGGTCCCAGGACCGCGAGTGGGACTTCCAGCACTGG              51
#> 2337:                               TGTAATGCATTTGAATTCTTT              21
#>             junction_aa junction_aa_length  v_score d_score j_score
#>    1:       CQQYGGSPYTF                 11  349.295      NA  66.059
#>    2:       CQQYGGSPYTF                 11  349.295      NA  44.909
#>    3:       CQQYGGSPYTF                 11  349.295      NA  39.141
#>    4:       CQQYGGSPYTF                 11  349.295      NA  44.909
#>    5:       CQQYGGSPYTF                 11  349.295      NA  50.677
#>   ---                                                              
#> 2333:           CQQYETF                  7  954.000      NA 143.000
#> 2334:           CNAYEFF                  7 1020.000      NA 100.000
#> 2335:   CARMGAAREWDFQYW                 15  846.000      NA 165.000
#> 2336: CARRMRSQDREWDFQHW                 17  819.000      NA 156.000
#> 2337:           CNAFEFF                  7  900.000      NA 118.000
#>                                                                                                                                                                                                      v_cigar
#>    1:                                                                                                                                                                                              287M38S3N
#>    2:                                                                                                                                                                                              287M38S3N
#>    3:                                                                                                                                                                                              287M38S3N
#>    4:                                                                                                                                                                                              287M38S3N
#>    5:                                                                                                                                                                                              287M38S3N
#>   ---                                                                                                                                                                                                       
#> 2333:                                       26=1X3=1X10=2X1=1X32=1X1=1X2=2X3=1X1=1X2=2X13=1X2=1X6=1X1=1X2=1X12=1X1=1X3=1X3=2X10=1X7=3X20=1X2=1X7=1X1=5X1=1X6=1X1=1X1=1X6=2X19=1X4=1X2=1X4=1X6=1X5=1X2=34S12N
#> 2334:                                                                       38=1X30=3D1X1=1X5=1X3=1X2=1X6=1X1=2X2=1X15=1X3=2X3=1X3=3X11=2X1=1X4=1X1=2X5=1X2=2X2=1X5=1X3=1X5=1X59=2X3=1X15=1X4=1X1=3X5=42S18N
#> 2335:           1X6=2X8=1X11=1X17=1X7=1X9=3X3=1X8=1X2=1X7=1X2=1X1=1X1=1X2=1X6=1X4=1X8=1X3=2X18=1X3=1X1=1X1=2X3=4X1=1X6=3X1=2X7=3X19=1X12=3X1=1X4=2X8=2X5=2X1=1X2=1X1=3X1=1X1=1X1=3X12=1X1=1X2=1X1=1X10=66S2N
#> 2336: 2=1X5=2X1=2X11=1X4=2X24=1X4=1X4=2X2=1X18=1X2=1X5=2X2=1X6=1X7=1X1=1X3=1X2=1X1=1X3=2X13=1X5=1X6=1X1=2X1=1X3=6X10=1X2=2X8=1X2=1X5=1X5=1X2=1X3=3X1=2X1=8X2=1X3=1X4=1X5=1X2=1X4=1X2=1X2=1X12=1X4=1X10=72S2N
#> 2337:                                               21=1X19=1X15=1X13=2X2=18D1=1X2=1X2=1X4=1X7=1X6=1X2=1X3=1X3=1X6=2X6=2X3=1X5=1X2=1X3=1X10=3X6=1X12=1X3=1X8=2X18=1X5=1X6=2X3=1X9=1X5=1X1=1X2=1X1=3X3=44S20N
#>                       d_cigar                         j_cigar v_support
#>    1:                    <NA>                       291S4N34M         0
#>    2:                    <NA>                       287S1N38M         0
#>    3:                    <NA>                       287S1N38M         0
#>    4:                    <NA>                       290S3N35M         0
#>    5:                    <NA>                       290S3N35M         0
#>   ---                                                                  
#> 2333:                    <NA>             276S5N21=1X4=1X6=1N        NA
#> 2334:                    <NA>      282S7N8=1X9=1X1=3X6=1X1=5S        NA
#> 2335:   294S4N2=1X1=2X6=54S2N        316S7N8=1X18=1X4=2X10=1N        NA
#> 2336: 301S10N3=1X1=2X3=55S11N 322S7N27=1X1=1X3=1X3=1X2=1X3=1N        NA
#> 2337:                    <NA>    260S2=3X1=1X2=1X15=1X10=2X5S        NA
#>       d_support j_support v_identity d_identity j_identity v_sequence_start
#>    1:        NA         0      88.85         NA    100.000                1
#>    2:        NA         0      88.85         NA     86.842                1
#>    3:        NA         0      88.85         NA     84.211                1
#>    4:        NA         0      88.85         NA     88.571                1
#>    5:        NA         0      88.85         NA     91.429                1
#>   ---                                                                      
#> 2333:        NA        NA      82.44         NA     91.180                1
#> 2334:        NA        NA      84.21         NA     73.680                1
#> 2335:        NA        NA      77.08          0     80.390                1
#> 2336:        NA        NA      76.04          0     78.430                1
#> 2337:        NA        NA      81.48         NA     78.950                1
#>       v_sequence_end v_germline_start v_germline_end d_sequence_start
#>    1:            287                1            287               NA
#>    2:            287                1            287               NA
#>    3:            287                1            287               NA
#>    4:            287                1            287               NA
#>    5:            287                1            287               NA
#>   ---                                                                
#> 2333:            275                1            323               NA
#> 2334:            276                1            321               NA
#> 2335:            294                1            318              295
#> 2336:            294                1            318              302
#> 2337:            259                1            319               NA
#>       d_sequence_end d_germline_start d_germline_end j_sequence_start
#>    1:             NA               NA             NA              292
#>    2:             NA               NA             NA              288
#>    3:             NA               NA             NA              288
#>    4:             NA               NA             NA              291
#>    5:             NA               NA             NA              291
#>   ---                                                                
#> 2333:             NA               NA             NA              277
#> 2334:             NA               NA             NA              283
#> 2335:            306                5             16              317
#> 2336:            311               11             20              323
#> 2337:             NA               NA             NA              261
#>       j_sequence_end j_germline_start j_germline_end fwr1_start fwr1_end
#>    1:            325                5             38          1       78
#>    2:            325                2             39          1       78
#>    3:            325                2             39          1       78
#>    4:            325                4             38          1       78
#>    5:            325                4             38          1       78
#>   ---                                                                   
#> 2333:            309                6             38          1       78
#> 2334:            313                8             38          1       72
#> 2335:            360                8             51          1       75
#> 2336:            366                8             51          1       75
#> 2337:            298                1             38          1       75
#>       cdr1_start cdr1_end fwr2_start fwr2_end cdr2_start cdr2_end fwr3_start
#>    1:         79       99        100      150        151      159        160
#>    2:         79       99        100      150        151      159        160
#>    3:         79       99        100      150        151      159        160
#>    4:         79       99        100      150        151      159        160
#>    5:         79       99        100      150        151      159        160
#>   ---                                                                       
#> 2333:         79       96         97      147        148      156        157
#> 2334:         73       99        100      150        151      159        160
#> 2335:         76       99        100      150        151      174        175
#> 2336:         76       99        100      150        151      174        175
#> 2337:         76       84         85      135        136      144        145
#>       fwr3_end fwr4_start fwr4_end cdr3_start cdr3_end     np1 np1_length
#>    1:      267        295      324        268      294    GTAC          4
#>    2:      267        295      324        268      294    <NA>          0
#>    3:      267        295      324        268      294    <NA>          0
#>    4:      267        295      324        268      294     GTA          3
#>    5:      267        295      324        268      294     GTA          3
#>   ---                                                                    
#> 2333:      264        280      309        265      279       G          1
#> 2334:      267        283      313        268      282  GAATTT          6
#> 2335:      288        328      360        289      327    <NA>          0
#> 2336:      288        334      366        289      333 AGAATGA          7
#> 2337:      252        268      298        253      267       T          1
#>               np2 np2_length run_application
#>    1:        <NA>         NA         IgBLAST
#>    2:        <NA>         NA         IgBLAST
#>    3:        <NA>         NA         IgBLAST
#>    4:        <NA>         NA         IgBLAST
#>    5:        <NA>         NA         IgBLAST
#>   ---                                       
#> 2333:        <NA>         NA         V-Quest
#> 2334:        <NA>         NA         V-Quest
#> 2335:  CGGGAGTGGG         10         V-Quest
#> 2336: CCGCGAGTGGG         11         V-Quest
#> 2337:        <NA>         NA         V-Quest
#>           mab_id mab_name_std mab_lanlid mab_hxb2_location
#>   1: cds_mab_332         CH01       2655             gp160
#>   2: cds_mab_332         CH01       2655             gp160
#>   3: cds_mab_332         CH01       2655             gp160
#>   4: cds_mab_332         CH01       2655             gp160
#>   5: cds_mab_332         CH01       2655             gp160
#>  ---                                                      
#> 777: cds_mab_670     VRC-PG20       3017               Env
#> 778: cds_mab_670     VRC-PG20       3017               Env
#> 779: cds_mab_670     VRC-PG20       3017               Env
#> 780: cds_mab_670     VRC-PG20       3017               Env
#> 781: cds_mab_670     VRC-PG20       3017               Env
#>                  mab_ab_binding_type mab_isotype mab_donorid mab_donor_species
#>   1: gp120 V2 (quaternary structure)        IgG1      CH0219             human
#>   2: gp120 V2 (quaternary structure)        IgG1      CH0219             human
#>   3: gp120 V2 (quaternary structure)        IgG1      CH0219             human
#>   4: gp120 V2 (quaternary structure)        IgG1      CH0219             human
#>   5: gp120 V2 (quaternary structure)        IgG1      CH0219             human
#>  ---                                                                          
#> 777:                     gp120 CD4bs        <NA>     IAVI 23             human
#> 778:                     gp120 CD4bs        <NA>     IAVI 23             human
#> 779:                     gp120 CD4bs        <NA>     IAVI 23             human
#> 780:                     gp120 CD4bs        <NA>     IAVI 23             human
#> 781:                     gp120 CD4bs        <NA>     IAVI 23             human
#>      mab_donor_clade      allele sequence_id percent_identity matches
#>   1:               A IGHD3-10*01 cds_seq_144            88.90      16
#>   2:               A IGHD3-10*02 cds_seq_144           100.00       9
#>   3:               A IGHD3-10*03 cds_seq_144            83.30      15
#>   4:               A IGHD3-16*03 cds_seq_144           100.00       7
#>   5:               A IGHD5-12*01 cds_seq_144           100.00       7
#>  ---                                                                 
#> 777:               A IGLV2-14*01 cds_seq_174            80.74     218
#> 778:               A IGLV2-14*02 cds_seq_174            81.11     219
#> 779:               A IGLV2-14*03 cds_seq_174            81.48     220
#> 780:               A IGLV2-23*01 cds_seq_174            80.74     218
#> 781:               A IGLV2-23*04 cds_seq_174            81.48     220
#>      alignment_length score run_application
#>   1:               18  23.8         IgBLAST
#>   2:                9  18.0         IgBLAST
#>   3:               18  18.0         IgBLAST
#>   4:                7  14.1         IgBLAST
#>   5:                7  14.1         IgBLAST
#>  ---                                       
#> 777:              270 882.0         V-Quest
#> 778:              270 891.0         V-Quest
#> 779:              270 900.0         V-Quest
#> 780:              270 882.0         V-Quest
#> 781:              270 900.0         V-Quest
#>           allele
#>   1:  IGHD1-1*01
#>   2: IGHD1-20*01
#>   3: IGHD1-26*01
#>   4:  IGHD1-7*01
#>   5: IGHD2-15*01
#>  ---            
#> 122: IGLV3-21*02
#> 123: IGLV3-21*03
#> 124: IGLV3-21*04
#> 125:  IGLV3-9*01
#> 126:  IGLV3-9*02
#>                                                                                                                                                                                                                                                                                                                                         allele_sequence_nt
#>   1:                                                                                                                                                                                                                                                                                                                                     GGTACAACTGGAACGAC
#>   2:                                                                                                                                                                                                                                                                                                                                     GGTATAACTGGAACGAC
#>   3:                                                                                                                                                                                                                                                                                                                                  GGTATAGTGGGAGCTACTAC
#>   4:                                                                                                                                                                                                                                                                                                                                     GGTATAACTGGAACTAC
#>   5:                                                                                                                                                                                                                                                                                                                       AGGATATTGTAGTGGTGGTAGCTGCTACTCC
#>  ---                                                                                                                                                                                                                                                                                                                                                      
#> 122: TCCTATGTGCTGACTCAGCCACCCTCG...GTGTCAGTGGCCCCAGGACAGACGGCCAGGATTACCTGTGGGGGAAACAACATTGGA..................AGTAAAAGTGTGCACTGGTACCAGCAGAAGCCAGGCCAGGCCCCTGTGCTGGTCGTCTATGATGAT.....................AGCGACCGGCCCTCAGGGATCCCT...GAGCGATTCTCTGGCTCCAAC......TCTGGGAACACGGCCACCCTGACCATCAGCAGGGTCGAAGCCGGGGATGAGGCCGACTATTACTGTCAGGTGTGGGATAGTAGTAGTGATCATCC
#> 123: TCCTATGTGCTGACTCAGCCACCCTCG...GTGTCAGTGGCCCCAGGAAAGACGGCCAGGATTACCTGTGGGGGAAACAACATTGGA..................AGTAAAAGTGTGCACTGGTACCAGCAGAAGCCAGGCCAGGCCCCTGTGCTGGTCGTCTATGATGAT.....................AGCGACCGGCCCTCAGGGATCCCT...GAGCGATTCTCTGGCTCCAAC......TCTGGGAACACGGCCACCCTGACCATCAGCAGGGTCGAAGCCGGGGATGAGGCCGACTATTACTGTCAGGTGTGGGATAGTAGTAGTGATCATCC
#> 124: TCCTATGTGCTGACTCAGCCACCCTCA...GTGTCAGTGGCCCCAGGAAAGACGGCCAGGATTACCTGTGGGGGAAACAACATTGGA..................AGTAAAAGTGTGCACTGGTACCAGCAGAAGCCAGGCCAGGCCCCTGTGCTGGTCATCTATTATGAT.....................AGCGACCGGCCCTCAGGGATCCCT...GAGCGATTCTCTGGCTCCAAC......TCTGGGAACACGGCCACCCTGACCATCAGCAGGGTCGAAGCCGGGGATGAGGCCGACTATTACTGTCAGGTGTGGGATAGTAGTAGTGATCATCC
#> 125:      TCCTATGAGCTGACTCAGCCACTCTCA...GTGTCAGTGGCCCTGGGACAGACGGCCAGGATTACCTGTGGGGGAAACAACATTGGA..................AGTAAAAATGTGCACTGGTACCAGCAGAAGCCAGGCCAGGCCCCTGTGCTGGTCATCTATAGGGAT.....................AGCAACCGGCCCTCTGGGATCCCT...GAGCGATTCTCTGGCTCCAAC......TCGGGGAACACGGCCACCCTGACCATCAGCAGAGCCCAAGCCGGGGATGAGGCTGACTATTACTGTCAGGTGTGGGACAGCAGCACTGCA
#> 126: TCCTATGAGCTGACTCAGCCACTCTCA...GTGTCAGTGGCCCTGGGACAGGCGGCCAGGATTACCTGTGGGGGAAACAACCTTGGA..................TATAAAAGTGTGCACTGGTACCAGCAGAAGCCAGGCCAGGCCCCTGTGCTGGTCATCTATAGGGAT.....................AACAACCGGCCCTCTGGGATCCCT...GAGCGATTCTCTGGCTCCAAC......TCGGGGAACACGGCCACCCTGACCATCAGCAGAGCCCAAGCCGGGGATGAGGCTGACTATTACTGTCAGGTGTGGGACAGCAGCACTGCACACCC
#>    run_application    run_information
#> 1:         IgBLAST  <data.frame[5x2]>
#> 2:         V-Quest <data.frame[10x2]>
```
 
Descriptons for the various fields in each of these objects can be found using the `variableDefinitions` active binding.


```
#>           query_name        field_name           caption description
#>   1:     mabMetadata         container            Folder        <NA>
#>   2:     mabMetadata            mab_id            Mab Id        <NA>
#>   3:     mabMetadata      mab_name_std      Mab Name Std        <NA>
#>   4:     mabMetadata        mab_lanlid        Mab Lanlid        <NA>
#>   5:     mabMetadata mab_hxb2_location Mab Hxb2 Location        <NA>
#>  ---                                                                
#> 132: alleleSequences      release_date      Release Date        <NA>
#> 133: alleleSequences         container            Folder        <NA>
#> 134:  runInformation   run_application   Run Application        <NA>
#> 135:  runInformation   run_information   Run Information        <NA>
#> 136:  runInformation         container            Folder        <NA>
```
