---
title: "Accessing Publication Data"
author:
  - Helen Miller
  - Jason Taylor
date: "2026-06-22"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Accessing Publication Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<style>
.sourceCode{
    overflow: clip;
}
</style>



DataSpace maintains a curated collection of relevant publications, which can be accessed through the [Publications page](https://dataspace.cavd.org/cds/CAVD/app.view?#learn/learn/Publication) through the app. Some publications include datasets which can be downloaded as a zip file. `DataSpaceR` provides an interface for browsing publications in DataSpace and downloading publication data where available.

## Browsing publications in DataSpace

The `DataSpaceConnection` object includes methods for browsing and downloading publications and publication data.

The examples below are meant to show abridged console output and are not intended to be exhaustive. 


``` r
library(DataSpaceR)
library(data.table)
con <- connectDS()
con
#> <DataSpaceConnection>
#>   URL: https://dataspace.cavd.org
#>   User: jmtaylor@scharp.org
#>   Available Studies: 397
#>     - 79 studies with data
#>     - 5074 subjects
#>     - 436354 data points
#>   Available Groups: 6
#>   Available Publications: 1910
#>     - 30 publications with data
#>   Available Connection objects:
#>     - availableDonors
#>     - availableGroups
#>     - availableMabMixtures
#>     - availableMabs
#>     - availablePublications
#>     - availableStudies
#>     - availableViruses
#>     - virusNameMappingTables
#>   Available Connection methods:
#>     - downloadPublicationData
#>     - getDaash
#>     - getDonors
#>     - getGroups
#>     - getMabs
#>     - getStudies
```

The `DataSpaceConnection` print method summarizes the publications and publication data. More details about publications can be accessed through `con$availablePublications`.


``` r
con$availablePublications
#>       publication_id  label   first_author
#>               <char> <char>         <char>
#>    1:           1006   <NA>       Abbink P
#>    2:           1303   <NA>      Abbott RK
#>    3:           1635   <NA>   Abernathy ME
#>    4:           1636   <NA>   Abernathy ME
#>    5:           1838   <NA>   Abernethy NF
#>   ---                                     
#> 1906:            276   <NA>      deCamp AC
#> 1907:           1029   <NA>    van Gils MJ
#> 1908:           1613   <NA> van Schooten J
#> 1909:           1618   <NA> van Schooten J
#> 1910:           1743   <NA> van der Laan L
#>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               all_authors
#>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <char>
#>    1:                                                                                                                                                                                                                                                                                                                                                                       Abbink P, Maxfield LF, Ng'ang'a D, Borducchi EN, Iampietro MJ, Bricault CA, Teigler JE, Blackmore S, Parenteau L, Wagh K, Handley SA, Zhao G, Virgin HW, Korber B, Barouch DH
#>    2:                                                                                                                                                                                                                                                                                                                                                                                                            Abbott RK, Lee JH, Menis S, Skog P, Rossi M, Ota T, Kulp DW, Bhullar D, Kalyuzhniy O, Havenar-Daughton C, Schief WR, Nemazee D, Crotty S
#>    3:                                                                                                                                                                                                                                                                                                                                                                                              Abernathy ME, Gristick HB, Vielmetter J, Keeffe JR, Gnanapragasam PNP, Lee YE, Escolano A, Gautam R, Seaman MS, Martin MA, Nussenzweig MC, Bjorkman PJ
#>    4:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Abernathy ME, Dam KMA, Esswein SR, Jette CA, Bjorkman PJ
#>    5:                                                                                                                                                                                                                                                                                                                                                                                                  Abernethy NF, McCloskey K, Trahey M, Rinn L, Broder G, Andrasik M, Laborde R, McGhan D, Spendolini S, Marimuthu S, Kanzmeier A, Hanes J, Kublin JG
#>   ---                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
#> 1906: deCamp AC, Rolland M, Edlefsen PT, Sanders-Buell E, Hall B, Magaret CA, Fiore-Gartland AJ, Juraska M, Carpp LN, Karuna ST, Bose M, LePore S, Miller S, O'Sullivan A, Poltavee K, Bai H, Dommaraju K, Zhao H, Wong K, Chen L, Ahmed H, Goodman D, Tay MZ, Gottardo R, Koup RA, Bailer R, Mascola JR, Graham BS, Roederer M, O'Connell RJ, Michael NL, Robb ML, Adams E, D'Souza P, Kublin J, Corey L, Geraghty DE, Frahm N, Tomaras GD, McElrath MJ, Frenkel L, Styrchak S, Tovanabutra S, Sobieszczyk ME, Hammer SM, Kim JH, Mullins JI, Gilbert PB
#> 1907:                                                                                                                                                                                                                         van Gils MJ, van den Kerkhof TL, Ozorowski G, Cottrell CA, Sok D, Pauthner M, Pallesen J, de Val N, Yasmeen A, de Taeye SW, Schorcht A, Gumbs S, Johanna I, Saye-Francisco K, Liang CH, Landais E, Nie X, Pritchard LK, Crispin M, Kelsoe G, Wilson IA, Schuitemaker H, Klasse PJ, Moore JP, Burton DR, Ward AB, Sanders RW
#> 1908:                                                                                                                                                                                                van Schooten J, Schorcht A, Farokhi E, Umotoy JC, Gao H, van den Kerkhof TLGM, Dorning J, Rijkhold Meesters TG, van der Woude P, Burger JA, Bijl T, Ghalaiyini R, Torrents de la Pena A, Turner HL, Labranche CC, Stanfield RL, Sok D, Schuitemaker H, Montefiori DC, Burton DR, Ozorowski G, Seaman MS, Wilson IA, Sanders RW, Ward AB, van Gils MJ
#> 1909:                                                                                                                                                                                                                  van Schooten J, Farokhi E, Schorcht A, van den Kerkhof TLGM, Gao H, van der Woude P, Burger JA, Rijkhold Meesters TG, Bijl T, Ghalaiyini R, Turner HL, Dorning J, van Schaik BDC, van Kampen AHC, Labranche CC, Stanfield RL, Sok D, Montefiori DC, Burton DR, Seaman MS, Ozorowski G, Wilson IA, Sanders RW, Ward AB, van Gils MJ
#> 1910:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 van der Laan L, Zhang W, Gilbert PB
#>                                                                                                                                                  title
#>                                                                                                                                                 <char>
#>    1:                                                                    Construction and evaluation of novel rhesus monkey adenovirus vaccine vectors
#>    2: Precursor frequency and affinity determine B Cell competitive fitness in germinal centers, tested with germline-targeting HIV vaccine immunogens
#>    3:                    Antibody elicited by HIV-1 immunogen vaccination in macaques displaces env fusion peptide and destroys a neutralizing epitope
#>    4:                     How antibodies recognize pathogenic viruses: Structural correlates of antibody neutralization of HIV-1, SARS-CoV-2, and Zika
#>    5:                                                                   Rapid development of a registry to accelerate COVID-19 vaccine clinical trials
#>   ---                                                                                                                                                 
#> 1906:               Sieve analysis of breakthrough HIV-1 sequences in HVTN 505 identifies vaccine pressure targeting the CD4 binding site of Env-gp120
#> 1907:                                             An HIV-1 antibody from an elite neutralizer implicates the fusion peptide as a site of vulnerability
#> 1908:                                            Complementary antibody lineages achieve neutralization breadth in an HIV-1 infected elite neutralizer
#> 1909:                           Identification of IOMA-class neutralizing antibodies targeting the CD4-binding site on the HIV-1 envelope glycoprotein
#> 1910:                                                       Nonparametric estimation of the causal effect of a stochastic threshold-based intervention
#>             journal publication_date                                         link pubmed_id related_studies studies_with_data
#>              <char>           <char>                                       <char>    <char>          <char>            <char>
#>    1:       J Virol         2015 Feb https://www.ncbi.nlm.nih.gov/pubmed/25410856  25410856            <NA>              <NA>
#>    2:      Immunity      2018 Jan 16 https://www.ncbi.nlm.nih.gov/pubmed/29287996  29287996            <NA>              <NA>
#>    3:  NPJ Vaccines      2021 Oct 25     https://pubmed.ncbi.nlm.nih.gov/34697307  34697307            <NA>              <NA>
#>    4:       Viruses      2021 Oct 19     https://pubmed.ncbi.nlm.nih.gov/34696536  34696536            <NA>              <NA>
#>    5: NPJ Digit Med      2025 May 06     https://pubmed.ncbi.nlm.nih.gov/40328984  40328984            <NA>              <NA>
#>   ---                                                                                                                        
#> 1906:      PLOS ONE      2017 Nov 17 https://www.ncbi.nlm.nih.gov/pubmed/29149197  29149197          vtn505            vtn505
#> 1907: Nat Microbiol      2016 Nov 14 https://www.ncbi.nlm.nih.gov/pubmed/27841852  27841852            <NA>              <NA>
#> 1908:   PLoS Pathog         2022 Nov     https://pubmed.ncbi.nlm.nih.gov/36395347  36395347          cvd850              <NA>
#> 1909:    Nat Commun      2022 Aug 03     https://pubmed.ncbi.nlm.nih.gov/35922441  35922441          cvd850              <NA>
#> 1910:    Biometrics         2023 Jun     https://pubmed.ncbi.nlm.nih.gov/35526218  35526218            <NA>              <NA>
#>       publication_data_available
#>                           <lgcl>
#>    1:                      FALSE
#>    2:                      FALSE
#>    3:                      FALSE
#>    4:                      FALSE
#>    5:                      FALSE
#>   ---                           
#> 1906:                      FALSE
#> 1907:                      FALSE
#> 1908:                      FALSE
#> 1909:                      FALSE
#> 1910:                      FALSE
```

This table summarizes all publications, providing some information like first author, journal where it was published, and title as a `data.table`. It also includes a pubmed url where available under `link`. Related studies under `related_studies`, and related studies with data available under `studies_with_data`.  We can use `data.table` methods to filter and sort this table to browse available publications.

For example, we can filter this table to view only publications related to a particular study:


``` r
vtn096_pubs <- con$availablePublications[grepl("vtn096", related_studies)]
vtn096_pubs
#>     publication_id                       label       first_author
#>             <char>                      <char>             <char>
#>  1:           1466   Cram 2019 (PLOS One) Data            Cram JA
#>  2:           1921                        <NA>            Huang Y
#>  3:            250                        <NA>            Huang Y
#>  4:            267                        <NA>            Huang Y
#>  5:            268                        <NA>            Huang Y
#>  6:           1728                        <NA>  Mayer-Blackwell K
#>  7:           1392 Pantaleo 2019 (Lancet) Data         Pantaleo G
#>  8:           1761                        <NA>          Seaton KE
#>  9:           1753                        <NA> Stranix-Chibanda L
#> 10:           1420                        <NA>         Westling T
#> 11:            281                        <NA>           Yates NL
#>                                                                                                                                                                                                                                                                                                                                                                                                    all_authors
#>                                                                                                                                                                                                                                                                                                                                                                                                         <char>
#>  1:                                                                                                                                                                                                                                                                                                        Cram JA, Fiore-Gartland AJ, Srinivasan S, Karuna S, Pantaleo G, Tomaras GD, Fredricks DN, Kublin JG
#>  2:                                                                                                                                                                                                                                                                                                                                                                                         Huang Y, Tarkhan A
#>  3:                                                                                                                                                                          Huang Y, DiazGranados C, Janes H, Huang Y, deCamp A, Metch B, Grant S, Sanchez B, Phogat S,  Koutsoukos M, Kanesa-Thasan N, Bourguignon P, Collard A, Buchbinder S, Tomaras GD, McElrath J, Gray G, Kublin J, Corey L, Gilbert PB
#>  4:                                                                                                                                                                                                                                                                                                    Huang Y, Zhang L, Janes H, Frahm N, Isaacs A, Kim JH, Montefiori D, McElrath MJ, Tomaras GD, Gilbert PB
#>  5:                                                                                                                                                                                                                                                                                                                                                                          Huang Y, Gilbert P, Fu R, Janes H
#>  6:                                                                                                                                                                                                                                                                     Mayer-Blackwell K, Johnson AM, Potchen N, Minot SS, Heptinstall J, Seaton K, Sawant S, Shen X, Tomaras GD, Fiore-Gartland A, Kublin JG
#>  7:                                                                                                                                                Pantaleo G, Janes H, Karuna S, Grant S, Ouedraogo GL, Allen M, Tomaras GD, Frahm N, Montefiori DC, Ferrari G, Ding S, Lee C, Robb ML, Esteban M, Wagner R, Bart PA, Rettby N, McElrath MJ, Gilbert PB, Kublin JG, Corey L, NIAID HIV Vaccine Trials Network
#>  8: Seaton KE, Deal A, Han X, Li SS, Clayton A, Heptinstall J, Duerr A, Allen MA, Shen X, Sawant S, Yates NL, Spearman P, Churchyard G, Goepfert PA, Maenza J, Gray G, Pantaleo G, Polakowski L, Robinson HL, Grant S,  Randhawa AK, Huang Y, Morgan C, Grunenberg N, Karuna S, Gilbert PB, McElrath MJ, Huang Y, Tomaras GD, NIAID HIV Vaccine Trials Network (HVTN) 076, 088, 086, 096, 097, 205 Study Teams
#>  9:                                                                                                                                                                                                                                                                                                                               Stranix-Chibanda L, Yu C, Brewinski Isaacs M, Allen M, Andriesen J, Walsh SR
#> 10:                                                                                                                                                                                                                                                                                                                                          Westling T, Juraska M, Seaton KE, Tomaras GD, Gilbert PB, Janes H
#> 11:                                                                                                                                                   Yates NL, deCamp AC, Korber BT, Liao HX, Irene C, Pinter A, Peacock J, Harris LJ, Sawant S, Hraber P, Shen X, Rerks-Ngarm S, Pitisuttithum P, Nitayapan S, Berman PW, Robb ML, Pantaleo G, Zolla-Pazner S, Haynes BF, Alam SM, Montefiori DC, Tomaras GD
#>                                                                                                                                                                                  title
#>                                                                                                                                                                                 <char>
#>  1:                                                                      Human gut microbiota is associated with HIV-reactive immunoglobulin at baseline and following HIV vaccination
#>  2:                                                                Methods for feature selection in down-selection of vaccine regimens based on multivariate immune response endpoints
#>  3:                                                                                                    Selection of HIV vaccine candidates for concurrent testing in an efficacy trial
#>  4:                                                                      Predictors of durable immune responses six months after the last vaccination in preventive HIV vaccine trials
#>  5:                                                   Statistical methods for down-selection of treatment regimens based on multiple endpoints, with application to HIV vaccine trials
#>  6:                                                                Multi-trial analysis of HIV-1 envelope gp41-reactive antibodies among global recipients of candidate HIV-1 vaccines
#>  7: Safety and immunogenicity of a multivalent HIV vaccine comprising envelope protein with either DNA or NYVAC vectors (HVTN 096): a phase 1b, double-blind, placebo-controlled trial
#>  8:                                                                                                               Meta-analysis of HIV-1 vaccine elicited mucosal antibodies in humans
#>  9:                 A retrospective analysis of incident pregnancy in Phase 1 and 2a HIV-1 vaccine study participants does not support concern for adverse pregnancy or birth outcomes
#> 10:                                                                                Methods for comparing durability of immune responses between vaccine regimens in early-phase trials
#> 11:                                                                   HIV-1 envelope glycoproteins from diverse clades differentiate antibody responses and durability among vaccinees
#>                  journal publication_date                                         link pubmed_id
#>                   <char>           <char>                                       <char>    <char>
#>  1:             PLoS One             2019 https://www.ncbi.nlm.nih.gov/pubmed/31869338  31869338
#>  2:          Stat Biosci             2020     https://pubmed.ncbi.nlm.nih.gov/32421096  32421096
#>  3:      Curr Opin Virol      2016 Jan 28  http://www.ncbi.nlm.nih.gov/pubmed/26827165  26827165
#>  4:              Vaccine      2017 Feb 22 https://www.ncbi.nlm.nih.gov/pubmed/28131393  28131393
#>  5:        Biostatistics       2017 Apr 1 https://www.ncbi.nlm.nih.gov/pubmed/27649715  27649715
#>  6:        Front Immunol             2022     https://pubmed.ncbi.nlm.nih.gov/36311720  36311720
#>  7:           Lancet HIV       2019 Oct 7 https://www.ncbi.nlm.nih.gov/pubmed/31601541  31601541
#>  8:         NPJ Vaccines      2021 Apr 15     https://pubmed.ncbi.nlm.nih.gov/33859204  33859204
#>  9:       BMC Infect Dis      2021 Aug 11     https://pubmed.ncbi.nlm.nih.gov/34380464  34380464
#> 10: Stat Methods Med Res       2019 Jan 9 https://www.ncbi.nlm.nih.gov/pubmed/30623732  30623732
#> 11:              J Virol      2018 Mar 28 https://www.ncbi.nlm.nih.gov/pubmed/29386288  29386288
#>                                                                                                                                                                                                                                                                                                                                                                                                                                     related_studies
#>                                                                                                                                                                                                                                                                                                                                                                                                                                              <char>
#>  1:                                                                                                                                                                                                                                                                                                                                                                                                                                          vtn096
#>  2:                                                                                                                                                                                                                                                                                                                                                                                                                                  mrv144, vtn096
#>  3:                                                                                                                                                                                                                                                                                                                                                                                                                                  mrv144, vtn096
#>  4:                                                                                                                                                                                                                                                                                                                                                                                                                          mrv144, vtn096, vtn205
#>  5:                                                                                                                                                                                                                                                                                                                                                                                                                                  mrv144, vtn096
#>  6:                                                                                                                                                                                                                                                                                                                                                  mrv144, vtn096, vtn097, vtn098, vtn100, vtn106, vtn107, vtn111, vtn122, vtn204, vtn205, vtn505
#>  7:                                                                                                                                                                                                                                                                                                                                                                                                                          mrv144, vtn096, vtn100
#>  8:                                                                                                                                                                                                                                                                                                                                                                                                  vtn076, vtn086, vtn088, vtn096, vtn097, vtn205
#>  9: vtn026, vtn039, vtn040, vtn041, vtn042, vtn044, vtn045, vtn048, vtn049, vtn050, vtn052, vtn054, vtn055, vtn056, vtn057, vtn059, vtn060, vtn063, vtn064, vtn065, vtn067, vtn068, vtn069, vtn070, vtn071, vtn072, vtn073, vtn073E, vtn076, vtn077, vtn078, vtn080, vtn082, vtn083, vtn084, vtn085, vtn086, vtn087, vtn088, vtn090, vtn092, vtn094, vtn096, vtn097, vtn098, vtn100, vtn105, vtn106, vtn110, vtn111, vtn112, vtn203, vtn204, vtn205
#> 10:                                                                                                                                                                                                                                                                                                                                                                                                                                  vtn094, vtn096
#> 11:                                                                                                                                                                                                                                                                                                                                                                                                                                  mrv144, vtn096
#>     studies_with_data publication_data_available
#>                <char>                     <lgcl>
#>  1:              <NA>                       TRUE
#>  2:              <NA>                      FALSE
#>  3:              <NA>                      FALSE
#>  4:              <NA>                      FALSE
#>  5:              <NA>                      FALSE
#>  6:    vtn097, vtn505                      FALSE
#>  7:              <NA>                       TRUE
#>  8:            vtn097                      FALSE
#>  9:    vtn097, vtn105                      FALSE
#> 10:              <NA>                      FALSE
#> 11:              <NA>                      FALSE
```

or publications that have related studies with integrated data in DataSpace:


``` r
pubs_with_study_data <- con$availablePublications[!is.na(studies_with_data)]
pubs_with_study_data |>
  head()
#>    publication_id                                   label      first_author
#>            <char>                                  <char>            <char>
#> 1:           1540 Andersen-Nissen 2021 (PLOS Pathog) Data Andersen-Nissen E
#> 2:            213                                    <NA>       Andrasik MP
#> 3:            218                                    <NA>       Andrasik MP
#> 4:            225                                    <NA>       Andrasik MP
#> 5:            226                                    <NA>         Arnold MP
#> 6:              7                                    <NA>          Asbach B
#>                                                                                                                                                                                                                                                                                                                                                            all_authors
#>                                                                                                                                                                                                                                                                                                                                                                 <char>
#> 1:                                                                                                                                         Andersen-Nissen E, Fiore-Gartland A, Ballweber Fleming L, Carpp LN, Naidoo AF, Harper MS, Voillet V, Grunenberg N, Laher F, Innes C, Bekker L-G, Kublin JG, Huang Y, Ferrari G, Tomaras GD, Gray G, Gilbert PB, McElrath MJ
#> 2:                                                                                                                                                                                                                                    Andrasik MP, Yoon R, Mooney J, Broder G, Bolton M, Votto T, Davis-Vogel A; HVTN 505 study team; NIAID HIV Vaccine Trials Network
#> 3:                                                                                                                                                                                                                                                                         Andrasik MP, Karuna ST, Nebergall M, Koblin BA, Kublin JG; NIAID HIV Vaccine Trials Network
#> 4:                                                                                                                                                                                                                                                                                       Andrasik MP, Chandler C, Powell B, Humes D, Wakefield S, Kripke K, Eckstein D
#> 5:                                                                                                                                                                                                                                                               Arnold MP, Andrasik M, Landers S, Karuna S, Mimiaga MJ, Wakefield S, Mayer K, Buchbinder S, Koblin BA
#> 6: Asbach B, Kliche A, Köstler J, Perdiguero B, Esteban M, Jacobs BL, Montefiori DC, LaBranche CC, Yates NL, Tomaras GD, Ferrari G, Foulds KE, Roederer M, Landucci G, Forthal DN, Seaman MS, Hawkins N, Self SG, Sato A, Gottardo R, Phogat S, Tartaglia J, Barnett SW, Burke B, Cristillo AD, Weiss DE, Francis J, Galmin L, Ding S, Heeney JL, Pantaleo G, Wagner R
#>                                                                                                                                            title
#>                                                                                                                                           <char>
#> 1:                                    Innate immune signatures to a partially-efficacious HIV vaccine predict correlates of HIV-1 infection risk
#> 2:         Exploring barriers and facilitators to participation of male-to-female transgender persons in preventive HIV vaccine clinical trials.
#> 3:        Behavioral risk assessment in HIV Vaccine Trials Network (HVTN) clinical trials: A qualitative study exploring HVTN staff perspectives
#> 4:                                                              Bridging the divide: HIV prevention research and Black men who have sex with men
#> 5:                                            Sources of racial/ethnic differences in HIV vaccine trial awareness: Exposure, attention, or both?
#> 6: Potential to streamline heterologous DNA prime and NYVAC/protein boost HIV vaccine regimens in rhesus macaques by employing improved antigens
#>               journal publication_date                                        link pubmed_id
#>                <char>           <char>                                      <char>    <char>
#> 1:        PLOS Pathog             2021                                        <NA>  33720973
#> 2:           Prev Sci         2014 Jun http://www.ncbi.nlm.nih.gov/pubmed/23446435  23446435
#> 3:            Vaccine      2013 Sep 13 http://www.ncbi.nlm.nih.gov/pubmed/23859840  23859840
#> 4: Am J Public Health         2014 Apr http://www.ncbi.nlm.nih.gov/pubmed/24524520  24524520
#> 5: Am J Public Health         2014 Aug http://www.ncbi.nlm.nih.gov/pubmed/24922153  24922153
#> 6:            J Virol      2016 Mar 28 http://www.ncbi.nlm.nih.gov/pubmed/26865719  26865719
#>                                                                   related_studies studies_with_data publication_data_available
#>                                                                            <char>            <char>                     <lgcl>
#> 1:                                                                         vtn097            vtn097                       TRUE
#> 2:                                                                         vtn505            vtn505                      FALSE
#> 3: vtn069, vtn404, vtn502, vtn503, vtn504, vtn505, vtn802, vtn903, vtn906, vtn907            vtn505                      FALSE
#> 4:                                                                         vtn505            vtn505                      FALSE
#> 5:                                                                         vtn505            vtn505                      FALSE
#> 6:                                                                 cvd277, cvd281    cvd277, cvd281                      FALSE
```

We can also use this information to connect to related studies and pull integrated data. Say we are interested in this Rouphael (2019) publication:


``` r
rouphael2019 <- con$availablePublications[first_author == "Rouphael NG"]
rouphael2019
#>    publication_id                              label first_author
#>            <char>                             <char>       <char>
#> 1:           1390 Rouphael 2019 (J Clin Invest) Data  Rouphael NG
#> 2:           1887                               <NA>  Rouphael NG
#>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            all_authors
#>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <char>
#> 1:                                                                                                                                                                          Rouphael NG, Morgan C, Li SS, Jensen R, Sanchez B, Karuna S, Swann E, Sobieszczyk ME, Frank I, Wilson GJ, Tieu HV, Maenza J, Norwood A, Kobie J, Sinangil F, Pantaleo G, Ding S, McElrath MJ, De Rosa SC, Montefiori DC, Ferrari G, Tomaras GD, Keefer MC, HVTN 105 Protocol Team and the NIAID HIV Vaccine Trials Network
#> 2: Rouphael NG, Branche AR, Diemert DJ, Falsey AR, Losada C, Baden LR,Frey SE, Whitaker JA, Little SJ, Kamidani S, Walter EB, Novak RM, Rupp R, Jackson LA, Babu TM, Kottkamp AC, Luetkemeyer AF, Immergluck LC, Presti RM, Bäcker M, Winokur PL, Mahgoub SM, Goepfert PA, Fusco DN, Atmar RL, Posavad CM, Netzl A, Smith DJ, Telu K, Mu J, McQuarrie LJ, Makowski M, Makhene MK, Crandon S, Montefiori DC, Roberts PC, Beigel JH; Coronavirus Variant Immunologic Landscape Trial (COVAIL) Study Team
#>                                                                                                                                 title
#>                                                                                                                                <char>
#> 1:                                      DNA priming and gp120 boosting induces HIV-specific antibodies in a randomized clinical trial
#> 2: Immunogenicity of a 2-dose regimen of Moderna mRNA beta/omicron BA.1 bivalent variant vaccine boost in a randomized clinical trial
#>          journal publication_date                                         link pubmed_id related_studies studies_with_data
#>           <char>           <char>                                       <char>    <char>          <char>            <char>
#> 1: J Clin Invest      2019 Sep 30 https://www.ncbi.nlm.nih.gov/pubmed/31566579  31566579          vtn105            vtn105
#> 2:  J Infect Dis      2023 Dec 20     https://pubmed.ncbi.nlm.nih.gov/37561027  37561027            <NA>              <NA>
#>    publication_data_available
#>                        <lgcl>
#> 1:                       TRUE
#> 2:                      FALSE
```

We can find this publication in the available publications table, determine related studies, and pull data for those studies where available.


``` r
## note here we are passing the column `related_studies` here where in
## this case has a single study_id. Other entries are comma separated
## and need to be split, for example:
## `con$availablePublications[,strsplit(related_studies, ", ") |> unlist() |> unique()]`
rouphael2019_study <- rouphael2019$related_studies |>  
  con$getStudies()
rouphael2019_study
#> <DataSpaceStudies>
#>   Studies: vtn105
#>   Available integrated datasets:
#>     - Binding Ab multiplex assay
#>     - Demographics
#>     - Intracellular Cytokine Staining
#>     - Neutralizing antibody
#>   Available non-integrated datasets:
#>   Available publication datasets:
#>     - Rouphael 2019 (J Clin Invest) Data
#>   Available Studies objects:
#>     - availableDatasets
#>     - datasets
#>     - studies
#>     - studyInfo
#>     - treatmentArm
#>     - variableDefinitions
#>   Available Studies methods:
#>     - loadAvailableDatasets
#>   Available Connection objects:
#>     - availableDonors
#>     - availableGroups
#>     - availableMabMixtures
#>     - availableMabs
#>     - availablePublications
#>     - availableStudies
#>     - availableViruses
#>     - virusNameMappingTables
#>   Available Connection methods:
#>     - downloadPublicationData
#>     - getDaash
#>     - getDonors
#>     - getGroups
#>     - getMabs
#>     - getStudies
rouphael2019_study$availableDatasets
#>    study_id     dataset_type assay_identifier                     assay_label
#>      <char>           <char>           <char>                          <char>
#> 1:   vtn105 Integrated Assay             BAMA      Binding Ab multiplex assay
#> 2:   vtn105 Integrated Assay     Demographics                    Demographics
#> 3:   vtn105 Integrated Assay              ICS Intracellular Cytokine Staining
#> 4:   vtn105 Integrated Assay              NAb           Neutralizing antibody
```

We can see that there are datasets available for this study. We can pull any of them using `rouphael2019_study$getDataset()`.

## Downloading Publication Data

DataSpace also includes publication datasets for some publications. The format of this data will vary from publication to publication, and is stored in a zip file. The `publication_data_available` field specifies publications where publication data is available.


``` r
pubs_with_data <- con$availablePublications[publication_data_available == TRUE]
```

Data for a publication can be accessed through by either passing a `publication_id` value or an `availablePublications` object to the `downloadPublicationData` connection method.

Here, we download data for publication with ID 1461 (Westling, 2020), and view the resulting downloads. Like the `get...` methods, you may pass the `availablePublications` object to download publication data listed in that table. 


``` r
publicationDataFiles <- con$availablePublications[label %like% "Westling 2020"] |>
  con$downloadPublicationData()
basename(publicationDataFiles)
#> [1] "Westling1461_publicationData.zip"
```

All zip files will include a file format document as a PDF, as well as a README. These documents will give an overview of the remaining contents of the files. In this case, data is separated by CD8+ T-cell responses and CD4+ T-cell responses, as described in the `README.txt`.
